import os
import logging
from contextlib import contextmanager
from datetime import datetime, timedelta

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

db_logger = logging.getLogger("db_errors")
db_logger.setLevel(logging.ERROR)
db_logger.propagate = False
_fh = logging.FileHandler("db_errors.log", encoding="utf-8")
_fh.setFormatter(logging.Formatter("%(asctime)s — %(message)s"))
db_logger.addHandler(_fh)


class DatabaseError(Exception):
    """Ошибка при работе с базой данных."""
    pass


_pool: ConnectionPool | None = None


def init_pool(dsn: str | None = None):
    """Инициализирует пул соединений. Вызывать один раз до init_db()."""
    global _pool
    if _pool is not None:
        return
    dsn = dsn or os.environ["DATABASE_URL"]
    _pool = ConnectionPool(dsn, min_size=1, max_size=10)


def close_pool():
    global _pool
    if _pool:
        _pool.close()
        _pool = None


@contextmanager
def get_connection():
    """Контекстный менеджер для подключения к БД."""
    if _pool is None:
        init_pool()
    conn = _pool.getconn()
    conn.row_factory = dict_row
    try:
        yield conn
        conn.commit()
    except psycopg.Error as e:
        conn.rollback()
        db_logger.error("Ошибка БД: %s", e)
        raise DatabaseError("Ошибка при работе с базой данных") from e
    except Exception:
        conn.rollback()
        raise
    finally:
        _pool.putconn(conn)


def init_db():
    """Создаёт таблицы если их нет."""
    stmts = [
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            telegram_id BIGINT UNIQUE NOT NULL,
            username TEXT,
            timezone TEXT DEFAULT 'UTC',
            reminder_mode TEXT DEFAULT 'once',
            time_morning TEXT DEFAULT '09:00',
            time_lunch TEXT DEFAULT '12:00',
            time_evening TEXT DEFAULT '18:00',
            time_night TEXT DEFAULT '22:00',
            daily_plan_enabled INTEGER DEFAULT 1,
            daily_plan_time TEXT DEFAULT '08:00',
            caregiver_enabled INTEGER DEFAULT 0,
            created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS dependents (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS medications (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            dosage TEXT NOT NULL,
            meal_relation TEXT NOT NULL CHECK(meal_relation IN ('before', 'after', 'with', 'any')),
            times_per_day INTEGER NOT NULL,
            active INTEGER DEFAULT 1,
            dependent_id INTEGER DEFAULT NULL,
            stock_qty REAL DEFAULT NULL,
            units_per_dose REAL DEFAULT 1,
            low_stock_days INTEGER DEFAULT 5,
            paused INTEGER DEFAULT 0,
            created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            FOREIGN KEY (user_id) REFERENCES users(id),
            FOREIGN KEY (dependent_id) REFERENCES dependents(id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS intake_log (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            medication_id INTEGER NOT NULL,
            scheduled_time TEXT NOT NULL,
            taken_at TEXT,
            status TEXT DEFAULT 'pending' CHECK(status IN ('taken', 'skipped', 'pending')),
            FOREIGN KEY (medication_id) REFERENCES medications(id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS schedule_rules (
            id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            medication_id INTEGER NOT NULL,
            reminder_time TEXT NOT NULL,
            frequency     TEXT NOT NULL DEFAULT 'daily',
            interval_days INTEGER,
            weekdays      TEXT,
            month_day     INTEGER,
            anchor_date   TEXT,
            dosage        TEXT,
            FOREIGN KEY (medication_id) REFERENCES medications(id)
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_medications_user_active ON medications(user_id, active)",
        "CREATE INDEX IF NOT EXISTS idx_medications_dependent ON medications(dependent_id)",
        "CREATE INDEX IF NOT EXISTS idx_schedule_rules_medication ON schedule_rules(medication_id)",
        "CREATE INDEX IF NOT EXISTS idx_intake_log_medication ON intake_log(medication_id, scheduled_time)",
        "CREATE INDEX IF NOT EXISTS idx_intake_log_taken_at ON intake_log(taken_at)",
    ]
    with get_connection() as conn:
        for stmt in stmts:
            conn.execute(stmt)


def migrate():
    """Добавляет новые колонки если их нет (миграция). Идемпотентна через IF NOT EXISTS."""
    with get_connection() as conn:
        for col, definition in [
            ("timezone",           "TEXT DEFAULT 'UTC'"),
            ("reminder_mode",      "TEXT DEFAULT 'once'"),
            ("time_morning",       "TEXT DEFAULT '09:00'"),
            ("time_lunch",         "TEXT DEFAULT '12:00'"),
            ("time_evening",       "TEXT DEFAULT '18:00'"),
            ("time_night",         "TEXT DEFAULT '22:00'"),
            ("daily_plan_enabled", "INTEGER DEFAULT 1"),
            ("daily_plan_time",    "TEXT DEFAULT '08:00'"),
            ("caregiver_enabled",  "INTEGER DEFAULT 0"),
        ]:
            conn.execute(
                f"ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS {col} {definition}"
            )

        conn.execute(
            "ALTER TABLE IF EXISTS schedule_rules ADD COLUMN IF NOT EXISTS dosage TEXT DEFAULT NULL"
        )

        for col, definition in [
            ("dependent_id",   "INTEGER DEFAULT NULL REFERENCES dependents(id)"),
            ("stock_qty",      "REAL DEFAULT NULL"),
            ("units_per_dose", "REAL DEFAULT 1"),
            ("low_stock_days", "INTEGER DEFAULT 5"),
            ("paused",         "INTEGER DEFAULT 0"),
        ]:
            conn.execute(
                f"ALTER TABLE IF EXISTS medications ADD COLUMN IF NOT EXISTS {col} {definition}"
            )

        conn.execute("DROP TABLE IF EXISTS schedules")


def get_or_create_user(telegram_id: int, username: str = None) -> int:
    """Возвращает id пользователя, создаёт если не существует."""
    with get_connection() as conn:
        row = conn.execute(
            """INSERT INTO users (telegram_id, username)
               VALUES (%s, %s)
               ON CONFLICT (telegram_id) DO UPDATE SET username = EXCLUDED.username
               RETURNING id""",
            (telegram_id, username)
        ).fetchone()
        return row["id"]


def get_reminder_mode(telegram_id: int) -> str:
    """Возвращает режим напоминаний: once | repeat."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT reminder_mode FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return row["reminder_mode"] if row else "once"


def set_reminder_mode(telegram_id: int, mode: str):
    """Устанавливает режим напоминаний."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET reminder_mode = %s WHERE telegram_id = %s",
            (mode, telegram_id)
        )


def set_user_timezone(telegram_id: int, timezone: str):
    """Сохраняет часовой пояс пользователя."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET timezone = %s WHERE telegram_id = %s",
            (timezone, telegram_id)
        )


def get_user_timezone(telegram_id: int) -> str:
    """Возвращает часовой пояс пользователя."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT timezone FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return row["timezone"] if row else "UTC"


def get_user_time_presets(telegram_id: int) -> dict:
    """Возвращает пресеты времени пользователя {morning, lunch, evening, night}."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT time_morning, time_lunch, time_evening, time_night FROM users WHERE telegram_id = %s",
            (telegram_id,)
        ).fetchone()
        if row:
            return {
                "morning": row["time_morning"] or "09:00",
                "lunch":   row["time_lunch"]   or "12:00",
                "evening": row["time_evening"] or "18:00",
                "night":   row["time_night"]   or "22:00",
            }
        return {"morning": "09:00", "lunch": "12:00", "evening": "18:00", "night": "22:00"}


def set_user_time_preset(telegram_id: int, slot: str, time: str) -> int:
    """Обновляет пресет времени и переносит существующие правила с прежнего времени на новое.

    Слоты хранятся в schedule_rules как конкретное время (снимок пресета на момент
    создания). Чтобы смена пресета «прокидывалась» в напоминания/список/план, все
    активные правила пользователя с reminder_time == старое значение пресета
    обновляются на новое. Возвращает число обновлённых правил.
    """
    col_map = {"morning": "time_morning", "lunch": "time_lunch",
               "evening": "time_evening", "night": "time_night"}
    col = col_map.get(slot)
    if not col:
        raise ValueError(f"Unknown slot: {slot}")
    with get_connection() as conn:
        row = conn.execute(
            f"SELECT id, {col} AS old FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if row is None:
            return 0
        old_time, user_id = row["old"], row["id"]
        conn.execute(f"UPDATE users SET {col} = %s WHERE telegram_id = %s", (time, telegram_id))
        if not old_time or old_time == time:
            return 0
        cur = conn.execute(
            """UPDATE schedule_rules SET reminder_time = %s
               WHERE reminder_time = %s
                 AND medication_id IN (
                     SELECT id FROM medications WHERE user_id = %s AND active = 1
                 )""",
            (time, old_time, user_id)
        )
        return cur.rowcount


def count_active_medications(user_id: int, dependent_id: int = None) -> int:
    """Возвращает количество активных лекарств для user_id (dependent_id=None — для себя)."""
    with get_connection() as conn:
        if dependent_id is None:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM medications WHERE user_id = %s AND active = 1 AND dependent_id IS NULL",
                (user_id,)
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM medications WHERE user_id = %s AND active = 1 AND dependent_id = %s",
                (user_id, dependent_id)
            ).fetchone()
        return row["n"]


def get_caregiver_mode(telegram_id: int) -> bool:
    """Возвращает True если caregiver-режим включён."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT caregiver_enabled FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return bool(row["caregiver_enabled"]) if row else False


def set_caregiver_mode(telegram_id: int, enabled: bool):
    """Включает или выключает caregiver-режим."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET caregiver_enabled = %s WHERE telegram_id = %s",
            (1 if enabled else 0, telegram_id)
        )


def get_dependents(telegram_id: int) -> list:
    """Возвращает список подопечных пользователя [{id, name}, ...]."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return []
        return conn.execute(
            "SELECT id, name FROM dependents WHERE user_id = %s ORDER BY id",
            (user["id"],)
        ).fetchall()


def count_dependents(telegram_id: int) -> int:
    """Возвращает количество подопечных пользователя."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return 0
        return conn.execute(
            "SELECT COUNT(*) AS n FROM dependents WHERE user_id = %s", (user["id"],)
        ).fetchone()["n"]


def add_dependent(telegram_id: int, name: str) -> int:
    """Добавляет подопечного. Возвращает id новой записи."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            raise DatabaseError("Пользователь не найден")
        row = conn.execute(
            "INSERT INTO dependents (user_id, name) VALUES (%s, %s) RETURNING id",
            (user["id"], name)
        ).fetchone()
        return row["id"]


def delete_dependent(telegram_id: int, dependent_id: int) -> list:
    """Удаляет подопечного и деактивирует его лекарства. Возвращает список ID лекарств."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return []
        user_id = user["id"]
        dep = conn.execute(
            "SELECT id FROM dependents WHERE id = %s AND user_id = %s", (dependent_id, user_id)
        ).fetchone()
        if not dep:
            return []
        med_ids = [r["id"] for r in conn.execute(
            "SELECT id FROM medications WHERE user_id = %s AND dependent_id = %s",
            (user_id, dependent_id)
        ).fetchall()]
        if med_ids:
            conn.execute("DELETE FROM intake_log WHERE medication_id = ANY(%s)", (med_ids,))
            conn.execute("DELETE FROM schedule_rules WHERE medication_id = ANY(%s)", (med_ids,))
            # dependent_id = NULL обязательно: иначе DELETE подопечного нарушит FK
            conn.execute(
                "UPDATE medications SET active = 0, dependent_id = NULL WHERE dependent_id = %s AND user_id = %s",
                (dependent_id, user_id)
            )
        conn.execute("DELETE FROM dependents WHERE id = %s", (dependent_id,))
        return med_ids


def add_medication(user_id: int, name: str, dosage: str,
                   meal_relation: str, times_per_day: int,
                   dependent_id: int = None) -> int:
    """Добавляет лекарство и возвращает его id."""
    with get_connection() as conn:
        row = conn.execute(
            """INSERT INTO medications (user_id, name, dosage, meal_relation, times_per_day, dependent_id)
               VALUES (%s, %s, %s, %s, %s, %s)
               RETURNING id""",
            (user_id, name, dosage, meal_relation, times_per_day, dependent_id)
        ).fetchone()
        return row["id"]


def add_schedule(medication_id: int, reminder_time: str):
    """Добавляет ежедневное напоминание (обратная совместимость)."""
    add_schedule_rule(medication_id, reminder_time, "daily")


def add_schedule_rule(medication_id: int, reminder_time: str, frequency: str,
                      interval_days: int = None, weekdays: str = None,
                      month_day: int = None, anchor_date: str = None, dosage: str = None):
    """Добавляет правило напоминания в schedule_rules."""
    with get_connection() as conn:
        conn.execute(
            """INSERT INTO schedule_rules
               (medication_id, reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
            (medication_id, reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage)
        )


def get_user_medications(user_id: int) -> list:
    """Возвращает активные лекарства пользователя с именем подопечного."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.*, d.name AS dependent_name
               FROM medications m
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.user_id = %s AND m.active = 1
               ORDER BY m.id""",
            (user_id,)
        ).fetchall()


def get_active_schedule_rows() -> list:
    """Все правила расписания активных лекарств + поля пользователя — один проход.

    Покрывает и напоминания (reminder_mode), и план дня (daily_plan_enabled /
    daily_plan_time). Фильтрация по плану дня выполняется в Python, без второго запроса.
    """
    with get_connection() as conn:
        return conn.execute(
            """SELECT u.telegram_id, u.timezone, u.reminder_mode,
                      u.daily_plan_enabled, u.daily_plan_time,
                      m.id AS medication_id, m.name, m.dosage AS med_dosage, m.meal_relation,
                      sr.reminder_time, sr.frequency, sr.interval_days,
                      sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage AS rule_dosage,
                      d.name AS dependent_name
               FROM schedule_rules sr
               JOIN medications m ON m.id = sr.medication_id
               JOIN users u ON u.id = m.user_id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.active = 1 AND m.paused = 0
               ORDER BY u.telegram_id, m.id, sr.reminder_time"""
        ).fetchall()


def deactivate_medication(medication_id: int, user_id: int):
    """Деактивирует лекарство и удаляет его расписание."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET active = 0 WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        )
        conn.execute(
            "DELETE FROM schedule_rules WHERE medication_id = %s",
            (medication_id,)
        )


def get_today_stats(user_id: int, start_utc: str, end_utc: str) -> list:
    """Возвращает статистику приёмов за сегодня (диапазон в UTC)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name, m.dosage, i.scheduled_time, i.status, i.taken_at
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s AND i.taken_at < %s
               ORDER BY i.taken_at""",
            (user_id, start_utc, end_utc)
        ).fetchall()


def get_history_detailed(user_id: int, since_utc: str) -> list:
    """Возвращает детальную историю начиная с since_utc (UTC строка)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name, m.dosage, m.id as med_id,
                      i.scheduled_time, i.status, i.taken_at,
                      d.name AS dependent_name
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s
               ORDER BY i.taken_at DESC, m.name, i.scheduled_time""",
            (user_id, since_utc)
        ).fetchall()


def get_history_by_days(user_id: int, days: int = 7) -> list:
    """Возвращает статистику по дням для каждого лекарства."""
    since = (datetime.utcnow() - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name, m.dosage,
                      LEFT(i.taken_at, 10) AS day,
                      SUM(CASE WHEN i.status = 'taken' THEN 1 ELSE 0 END) AS taken,
                      SUM(CASE WHEN i.status = 'skipped' THEN 1 ELSE 0 END) AS skipped,
                      COUNT(*) AS total
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s
               GROUP BY m.id, m.name, LEFT(i.taken_at, 10)
               ORDER BY m.name, day DESC""",
            (user_id, since)
        ).fetchall()


def get_history(user_id: int, days: int = 7) -> list:
    """Возвращает статистику приёмов за последние N дней."""
    since = (datetime.utcnow() - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name,
                      COUNT(*) AS total,
                      SUM(CASE WHEN i.status = 'taken' THEN 1 ELSE 0 END) AS taken,
                      SUM(CASE WHEN i.status = 'skipped' THEN 1 ELSE 0 END) AS skipped
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s
               GROUP BY m.id, m.name
               ORDER BY m.name""",
            (user_id, since)
        ).fetchall()


def set_medication_paused(medication_id: int, user_id: int, paused: bool):
    """Ставит лекарство на паузу / снимает с паузы (F4)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET paused = %s WHERE id = %s AND user_id = %s",
            (1 if paused else 0, medication_id, user_id)
        )


def get_medication_by_id(medication_id: int, user_id: int):
    """Возвращает лекарство по id."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT * FROM medications WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        ).fetchone()


def get_schedules_by_medication(medication_id: int) -> list:
    """Возвращает правила расписания для лекарства."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage
               FROM schedule_rules WHERE medication_id = %s""",
            (medication_id,)
        ).fetchall()


def get_rules_grouped_for_user(user_id: int) -> dict:
    """Возвращает {medication_id: [rule, ...]} для всех активных лекарств пользователя одним запросом."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT sr.medication_id, sr.reminder_time, sr.frequency,
                      sr.interval_days, sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage
               FROM schedule_rules sr
               JOIN medications m ON m.id = sr.medication_id
               WHERE m.user_id = %s AND m.active = 1
               ORDER BY sr.medication_id""",
            (user_id,)
        ).fetchall()
    grouped: dict = {}
    for r in rows:
        grouped.setdefault(r["medication_id"], []).append(r)
    return grouped


# ── Соблюдение режима / adherence (F3) ──────────────────────────────────────

def get_adherence_rules(user_id: int) -> list:
    """Правила активных лекарств пользователя + created_at/имя/подопечный (F3)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.id AS medication_id, m.name, m.dosage AS med_dosage,
                      m.created_at, d.name AS dependent_name,
                      sr.reminder_time, sr.frequency, sr.interval_days,
                      sr.weekdays, sr.month_day, sr.anchor_date
               FROM medications m
               JOIN schedule_rules sr ON sr.medication_id = m.id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.user_id = %s AND m.active = 1 AND m.paused = 0
               ORDER BY m.id""",
            (user_id,)
        ).fetchall()


def get_taken_intakes(user_id: int, start_utc: str, end_utc: str) -> list:
    """(medication_id, taken_at) для status='taken' в окне — для календаря отчёта врача (F1)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT i.medication_id AS mid, i.taken_at
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s AND i.status = 'taken'
                 AND i.taken_at >= %s AND i.taken_at < %s""",
            (user_id, start_utc, end_utc)
        ).fetchall()


def get_taken_counts(user_id: int, start_utc: str, end_utc: str) -> dict:
    """{medication_id: число приёмов status='taken' за [start_utc, end_utc)} — числитель adherence (F3)."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT i.medication_id AS mid, COUNT(*) AS cnt
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s AND i.status = 'taken'
                 AND i.taken_at >= %s AND i.taken_at < %s
               GROUP BY i.medication_id""",
            (user_id, start_utc, end_utc)
        ).fetchall()
    return {r["mid"]: r["cnt"] for r in rows}


def get_streak_rows(user_id: int) -> list:
    """Правила активных непаузных лекарств + dependent_id/имя/created_at — для серий (F2)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.id AS medication_id, m.dependent_id, m.created_at,
                      d.name AS dependent_name,
                      sr.reminder_time, sr.frequency, sr.interval_days,
                      sr.weekdays, sr.month_day, sr.anchor_date
               FROM medications m
               JOIN schedule_rules sr ON sr.medication_id = m.id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.user_id = %s AND m.active = 1 AND m.paused = 0
               ORDER BY m.id""",
            (user_id,)
        ).fetchall()


def get_intake_statuses_window(user_id: int, start_utc: str, end_utc: str) -> list:
    """Записи intake_log (mid, scheduled_time, status, taken_at) пользователя за окно — для серий (F2)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT i.medication_id, i.scheduled_time, i.status, i.taken_at
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s AND i.taken_at >= %s AND i.taken_at < %s""",
            (user_id, start_utc, end_utc)
        ).fetchall()


def update_medication(medication_id: int, user_id: int, name: str, dosage: str,
                      meal_relation: str, times_per_day: int, new_rules: list):
    """Обновляет лекарство и его расписание. new_rules — список dict с полями rule."""
    with get_connection() as conn:
        conn.execute(
            """UPDATE medications SET name=%s, dosage=%s, meal_relation=%s, times_per_day=%s
               WHERE id=%s AND user_id=%s""",
            (name, dosage, meal_relation, times_per_day, medication_id, user_id)
        )
        conn.execute("DELETE FROM schedule_rules WHERE medication_id=%s", (medication_id,))
        for rule in new_rules:
            conn.execute(
                """INSERT INTO schedule_rules
                   (medication_id, reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                (medication_id, rule["reminder_time"], rule.get("frequency", "daily"),
                 rule.get("interval_days"), rule.get("weekdays"),
                 rule.get("month_day"), rule.get("anchor_date"), rule.get("dosage"))
            )


def get_user_settings_row(telegram_id: int):
    """Возвращает строку настроек пользователя одним запросом (для экрана /settings)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT timezone, reminder_mode,
                      time_morning, time_lunch, time_evening, time_night,
                      daily_plan_enabled, daily_plan_time, caregiver_enabled
               FROM users WHERE telegram_id = %s""",
            (telegram_id,)
        ).fetchone()


def get_daily_plan_settings(telegram_id: int) -> dict:
    """Возвращает настройки плана дня: {enabled, time}."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT daily_plan_enabled, daily_plan_time FROM users WHERE telegram_id = %s",
            (telegram_id,)
        ).fetchone()
        if row:
            return {"enabled": bool(row["daily_plan_enabled"]), "time": row["daily_plan_time"] or "08:00"}
        return {"enabled": True, "time": "08:00"}


def set_daily_plan_enabled(telegram_id: int, enabled: bool):
    """Включает или выключает план дня."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET daily_plan_enabled = %s WHERE telegram_id = %s",
            (1 if enabled else 0, telegram_id)
        )


def set_daily_plan_time(telegram_id: int, time_str: str):
    """Устанавливает время отправки плана дня."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET daily_plan_time = %s WHERE telegram_id = %s",
            (time_str, telegram_id)
        )


def get_schedules_for_user(telegram_id: int) -> list:
    """Возвращает все активные правила расписания для одного пользователя."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT u.telegram_id, u.timezone,
                      m.id AS medication_id, m.name, m.dosage AS med_dosage, m.meal_relation,
                      sr.reminder_time, sr.frequency, sr.interval_days,
                      sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage AS rule_dosage,
                      d.name AS dependent_name
               FROM users u
               JOIN medications m ON m.user_id = u.id AND m.active = 1
               JOIN schedule_rules sr ON sr.medication_id = m.id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE u.telegram_id = %s AND m.paused = 0
               ORDER BY m.id, sr.reminder_time""",
            (telegram_id,)
        ).fetchall()


def delete_user_data(telegram_id: int) -> list:
    """Удаляет все данные пользователя. Возвращает список ID удалённых лекарств."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return []
        user_id = user["id"]
        med_ids = [r["id"] for r in conn.execute(
            "SELECT id FROM medications WHERE user_id = %s", (user_id,)
        ).fetchall()]
        if med_ids:
            conn.execute("DELETE FROM intake_log WHERE medication_id = ANY(%s)", (med_ids,))
            conn.execute("DELETE FROM schedule_rules WHERE medication_id = ANY(%s)", (med_ids,))
            conn.execute("DELETE FROM medications WHERE user_id = %s", (user_id,))
        conn.execute("DELETE FROM dependents WHERE user_id = %s", (user_id,))
        conn.execute("DELETE FROM users WHERE telegram_id = %s", (telegram_id,))
        return med_ids


def get_admin_stats() -> dict:
    """Возвращает статистику для админ-панели."""
    today = datetime.utcnow().strftime('%Y-%m-%d')
    with get_connection() as conn:
        total_users = conn.execute("SELECT COUNT(*) AS n FROM users").fetchone()["n"]
        total_meds = conn.execute(
            "SELECT COUNT(*) AS n FROM medications WHERE active = 1"
        ).fetchone()["n"]
        active_today = conn.execute(
            """SELECT COUNT(DISTINCT m.user_id) AS n FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE LEFT(i.taken_at, 10) = %s""",
            (today,)
        ).fetchone()["n"]
        return {"total_users": total_users, "total_meds": total_meds, "active_today": active_today}


def get_today_intake_statuses(telegram_id: int, start_utc: str, end_utc: str) -> dict:
    """Возвращает {(medication_id, scheduled_time): status} для записей в локальных сутках пользователя."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT i.medication_id, i.scheduled_time, i.status
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               JOIN users u ON u.id = m.user_id
               WHERE u.telegram_id = %s AND i.taken_at >= %s AND i.taken_at < %s""",
            (telegram_id, start_utc, end_utc)
        ).fetchall()
    return {(r["medication_id"], r["scheduled_time"]): r["status"] for r in rows}


def log_intake(medication_id: int, scheduled_time: str, status: str,
               start_utc: str, end_utc: str):
    """Записывает факт приёма или пропуска лекарства. Обновляет запись если уже есть за сегодня.

    Возвращает прежний статус записи за сегодня (или None, если записи не было).
    """
    now_utc = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
    with get_connection() as conn:
        existing = conn.execute(
            """SELECT id, status FROM intake_log
               WHERE medication_id = %s AND scheduled_time = %s
               AND taken_at >= %s AND taken_at < %s""",
            (medication_id, scheduled_time, start_utc, end_utc)
        ).fetchone()
        if existing:
            conn.execute(
                "UPDATE intake_log SET status = %s, taken_at = %s WHERE id = %s",
                (status, now_utc, existing["id"])
            )
            return existing["status"]
        conn.execute(
            """INSERT INTO intake_log (medication_id, scheduled_time, status, taken_at)
               VALUES (%s, %s, %s, %s)""",
            (medication_id, scheduled_time, status, now_utc)
        )
        return None


# ── Учёт запаса таблеток (F5) ───────────────────────────────────────────────

def set_medication_stock(medication_id: int, user_id: int, stock_qty: float):
    """Устанавливает остаток (включает трекинг)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET stock_qty = %s WHERE id = %s AND user_id = %s",
            (stock_qty, medication_id, user_id)
        )


def add_medication_stock(medication_id: int, user_id: int, amount: float):
    """Прибавляет amount к остатку (пополнение упаковкой). Если трекинг был выключен — включает."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT stock_qty FROM medications WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        ).fetchone()
        base = (row["stock_qty"] if row and row["stock_qty"] is not None else 0)
        conn.execute(
            "UPDATE medications SET stock_qty = %s WHERE id = %s AND user_id = %s",
            (base + amount, medication_id, user_id)
        )


def set_units_per_dose(medication_id: int, user_id: int, units: float):
    """Устанавливает расход единиц за один приём."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET units_per_dose = %s WHERE id = %s AND user_id = %s",
            (units, medication_id, user_id)
        )


def set_low_stock_days(medication_id: int, user_id: int, days: int):
    """Устанавливает порог предупреждения (в днях)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET low_stock_days = %s WHERE id = %s AND user_id = %s",
            (days, medication_id, user_id)
        )


def disable_stock_tracking(medication_id: int, user_id: int):
    """Выключает учёт запаса (stock_qty = NULL)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET stock_qty = NULL WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        )


def apply_intake_stock(medication_id: int, new_status: str, old_status):
    """Корректирует остаток при отметке приёма. Возвращает dict состояния после или None.

    Идемпотентно: списывает units_per_dose только при переходе в `taken`,
    возвращает при уходе из `taken`. `changed=True` — если остаток изменился.
    None — если трекинг выключен (stock_qty IS NULL) или лекарство не найдено.
    """
    with get_connection() as conn:
        row = conn.execute(
            "SELECT stock_qty, units_per_dose, low_stock_days FROM medications WHERE id = %s",
            (medication_id,)
        ).fetchone()
        if row is None or row["stock_qty"] is None:
            return None
        units = row["units_per_dose"] or 1
        qty = row["stock_qty"]
        changed = False
        if new_status == "taken" and old_status != "taken":
            qty = max(0, qty - units)
            changed = True
        elif old_status == "taken" and new_status != "taken":
            qty = qty + units
            changed = True
        if changed:
            conn.execute("UPDATE medications SET stock_qty = %s WHERE id = %s", (qty, medication_id))
        return {"stock_qty": qty, "units_per_dose": units,
                "low_stock_days": row["low_stock_days"], "changed": changed}
