import os
import secrets
import sys
import logging
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

db_logger = logging.getLogger("db_errors")
db_logger.setLevel(logging.ERROR)
db_logger.propagate = False
_sh = logging.StreamHandler(sys.stderr)
_sh.setFormatter(logging.Formatter("%(asctime)s — %(message)s"))
db_logger.addHandler(_sh)


class DatabaseError(Exception):
    """Ошибка при работе с базой данных."""
    pass


_pool: ConnectionPool | None = None

# F7: код для опекуна — 8 символов без визуально схожих знаков
_CODE_CHARS = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"


def _gen_caregiver_code() -> str:
    c = "".join(secrets.choice(_CODE_CHARS) for _ in range(8))
    return f"{c[:4]}-{c[4:]}"


def init_pool(dsn: str | None = None):
    """Инициализирует пул соединений. Вызывать один раз до init_db()."""
    global _pool
    if _pool is not None:
        return
    dsn = dsn or os.environ["DATABASE_URL"]
    _pool = ConnectionPool(dsn, min_size=1, max_size=10, open=True)


def close_pool():
    global _pool
    if _pool:
        _pool.close()
        _pool = None


@contextmanager
def get_connection():
    """Контекстный менеджер для подключения к БД."""
    if _pool is None:
        init_pool()
    conn = _pool.getconn()
    conn.row_factory = dict_row
    try:
        yield conn
        conn.commit()
    except psycopg.Error as e:
        conn.rollback()
        db_logger.error("Ошибка БД: %s", e)
        raise DatabaseError("Ошибка при работе с базой данных") from e
    except Exception:
        conn.rollback()
        raise
    finally:
        _pool.putconn(conn)


def init_db():
    """Создаёт таблицы если их нет."""
    stmts = [
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            telegram_id BIGINT UNIQUE NOT NULL,
            username TEXT,
            timezone TEXT DEFAULT 'UTC',
            reminder_mode TEXT DEFAULT 'once',
            time_morning TEXT DEFAULT '09:00',
            time_lunch TEXT DEFAULT '12:00',
            time_evening TEXT DEFAULT '18:00',
            time_night TEXT DEFAULT '22:00',
            daily_plan_enabled INTEGER DEFAULT 1,
            daily_plan_time TEXT DEFAULT '08:00',
            caregiver_enabled INTEGER DEFAULT 0,
            hearts INTEGER DEFAULT 0,
            strict_mode INTEGER DEFAULT 0,
            strict_mode_hours INTEGER DEFAULT 2,
            reminder_repeat_hours INTEGER DEFAULT 2,
            created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            caregiver_code TEXT DEFAULT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS dependents (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS caregiver_links (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            caregiver_id INTEGER NOT NULL REFERENCES users(id),
            dependent_id INTEGER NOT NULL REFERENCES users(id),
            status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'active', 'declined')),
            break_requested INTEGER DEFAULT 0,
            created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            UNIQUE(caregiver_id, dependent_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS medications (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            dosage TEXT NOT NULL,
            meal_relation TEXT NOT NULL CHECK(meal_relation IN ('before', 'after', 'with', 'any')),
            times_per_day INTEGER NOT NULL,
            active INTEGER DEFAULT 1,
            dependent_id INTEGER DEFAULT NULL,
            stock_qty REAL DEFAULT NULL,
            units_per_dose REAL DEFAULT 1,
            low_stock_days INTEGER DEFAULT 5,
            unit_dose_value REAL DEFAULT NULL,
            unit_dose_label TEXT DEFAULT 'мг',
            dose_per_intake REAL DEFAULT NULL,
            pack_size REAL DEFAULT NULL,
            course_total INTEGER DEFAULT NULL,
            paused INTEGER DEFAULT 0,
            created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
            FOREIGN KEY (user_id) REFERENCES users(id),
            FOREIGN KEY (dependent_id) REFERENCES dependents(id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS intake_log (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            medication_id INTEGER NOT NULL,
            scheduled_time TEXT NOT NULL,
            taken_at TEXT,
            status TEXT DEFAULT 'pending' CHECK(status IN ('taken', 'skipped', 'pending')),
            FOREIGN KEY (medication_id) REFERENCES medications(id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS schedule_rules (
            id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            medication_id INTEGER NOT NULL,
            reminder_time TEXT NOT NULL,
            frequency     TEXT NOT NULL DEFAULT 'daily',
            interval_days INTEGER,
            weekdays      TEXT,
            month_day     INTEGER,
            anchor_date   TEXT,
            dosage        TEXT,
            dose_cycle    TEXT,
            FOREIGN KEY (medication_id) REFERENCES medications(id)
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_medications_user_active ON medications(user_id, active)",
        "CREATE INDEX IF NOT EXISTS idx_medications_dependent ON medications(dependent_id)",
        "CREATE INDEX IF NOT EXISTS idx_schedule_rules_medication ON schedule_rules(medication_id)",
        "CREATE INDEX IF NOT EXISTS idx_intake_log_medication ON intake_log(medication_id, scheduled_time)",
        "CREATE INDEX IF NOT EXISTS idx_intake_log_taken_at ON intake_log(taken_at)",
        # AX1: одна запись на (лекарство, слот, день) — защита от дублей при
        # параллельных отметках. День = UTC-дата taken_at (одновременные вставки
        # совпадают по моменту → по дню), local-day всегда укладывается в один слот.
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_intake_log_slot_day "
        "ON intake_log (medication_id, scheduled_time, (LEFT(taken_at, 10)))",
    ]
    with get_connection() as conn:
        for stmt in stmts:
            conn.execute(stmt)


def migrate():
    """Добавляет новые колонки если их нет (миграция). Идемпотентна через IF NOT EXISTS."""
    with get_connection() as conn:
        for col, definition in [
            ("timezone",           "TEXT DEFAULT 'UTC'"),
            ("reminder_mode",      "TEXT DEFAULT 'once'"),
            ("time_morning",       "TEXT DEFAULT '09:00'"),
            ("time_lunch",         "TEXT DEFAULT '12:00'"),
            ("time_evening",       "TEXT DEFAULT '18:00'"),
            ("time_night",         "TEXT DEFAULT '22:00'"),
            ("daily_plan_enabled", "INTEGER DEFAULT 1"),
            ("daily_plan_time",    "TEXT DEFAULT '08:00'"),
            ("caregiver_enabled",  "INTEGER DEFAULT 0"),
            ("hearts",             "INTEGER DEFAULT 0"),
            ("strict_mode",               "INTEGER DEFAULT 0"),
            ("strict_mode_hours",         "INTEGER DEFAULT 2"),
            ("strict_mode_minutes",       "INTEGER DEFAULT 0"),
            ("reminder_repeat_hours",     "INTEGER DEFAULT 2"),
            ("reminder_repeat_minutes",   "INTEGER DEFAULT 0"),
            ("wishes_enabled",            "INTEGER DEFAULT 0"),
            ("wishes_tg_notify",          "INTEGER DEFAULT 0"),
        ]:
            conn.execute(
                f"ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS {col} {definition}"
            )

        conn.execute(
            "ALTER TABLE IF EXISTS schedule_rules ADD COLUMN IF NOT EXISTS dosage TEXT DEFAULT NULL"
        )
        # F11-F: чередование доз по дням (CSV чисел; индекс=(день−anchor)%len)
        conn.execute(
            "ALTER TABLE IF EXISTS schedule_rules ADD COLUMN IF NOT EXISTS dose_cycle TEXT DEFAULT NULL"
        )

        for col, definition in [
            ("dependent_id",   "INTEGER DEFAULT NULL REFERENCES dependents(id)"),
            ("stock_qty",      "REAL DEFAULT NULL"),
            ("units_per_dose", "REAL DEFAULT 1"),
            ("low_stock_days", "INTEGER DEFAULT 5"),
            ("unit_dose_value", "REAL DEFAULT NULL"),
            ("unit_dose_label", "TEXT DEFAULT 'мг'"),
            ("dose_per_intake", "REAL DEFAULT NULL"),
            ("pack_size",       "REAL DEFAULT NULL"),
            ("course_total",    "INTEGER DEFAULT NULL"),
            ("paused",         "INTEGER DEFAULT 0"),
        ]:
            conn.execute(
                f"ALTER TABLE IF EXISTS medications ADD COLUMN IF NOT EXISTS {col} {definition}"
            )

        conn.execute("DROP TABLE IF EXISTS schedules")

        # F7: caregiver связи
        conn.execute(
            "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS caregiver_code TEXT DEFAULT NULL"
        )
        conn.execute(
            """CREATE TABLE IF NOT EXISTS caregiver_links (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                caregiver_id INTEGER NOT NULL REFERENCES users(id),
                dependent_id INTEGER NOT NULL REFERENCES users(id),
                status TEXT NOT NULL DEFAULT 'pending'
                    CHECK(status IN ('pending', 'active', 'declined')),
                break_requested INTEGER DEFAULT 0,
                created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
                UNIQUE(caregiver_id, dependent_id)
            )"""
        )
        conn.execute(
            "ALTER TABLE IF EXISTS caregiver_links "
            "ADD COLUMN IF NOT EXISTS break_requested INTEGER DEFAULT 0"
        )
        conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_caregiver_code "
            "ON users(caregiver_code) WHERE caregiver_code IS NOT NULL"
        )

        # AX1: чистим существующие дубли (med, scheduled_time, UTC-день) перед
        # созданием UNIQUE-индекса — оставляем самую свежую запись (max id).
        conn.execute(
            """DELETE FROM intake_log a USING intake_log b
               WHERE a.id < b.id
                 AND a.medication_id = b.medication_id
                 AND a.scheduled_time = b.scheduled_time
                 AND LEFT(a.taken_at, 10) = LEFT(b.taken_at, 10)"""
        )
        conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_intake_log_slot_day "
            "ON intake_log (medication_id, scheduled_time, (LEFT(taken_at, 10)))"
        )

        # F8: dep sharing
        conn.execute(
            "ALTER TABLE IF EXISTS dependents ADD COLUMN IF NOT EXISTS share_code TEXT DEFAULT NULL"
        )
        conn.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_dependents_share_code "
            "ON dependents(share_code) WHERE share_code IS NOT NULL"
        )
        conn.execute(
            """CREATE TABLE IF NOT EXISTS dependent_shares (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                dep_id INTEGER NOT NULL REFERENCES dependents(id) ON DELETE CASCADE,
                owner_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                viewer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                status TEXT NOT NULL DEFAULT 'pending'
                    CHECK(status IN ('pending', 'active', 'declined')),
                created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
                UNIQUE(dep_id, viewer_user_id)
            )"""
        )

        # F12a: ачивки (бейджи по абсолютным порогам)
        conn.execute(
            """CREATE TABLE IF NOT EXISTS achievements (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NOT NULL REFERENCES users(id),
                code TEXT NOT NULL,
                unlocked_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
                UNIQUE(user_id, code)
            )"""
        )

        # Ф15: соцмеханика пожеланий (тестовый функционал за тоглом wishes_enabled)
        conn.execute(
            "ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS wishes_enabled INTEGER DEFAULT 0"
        )
        conn.execute(
            """CREATE TABLE IF NOT EXISTS wishes_sent (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                sender_id INTEGER NOT NULL REFERENCES users(id),
                recipient_id INTEGER NOT NULL REFERENCES users(id),
                preset_code TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'delivered'
                    CHECK(status IN ('delivered', 'reacted')),
                reaction TEXT DEFAULT NULL CHECK(reaction IN ('helped', 'supported')),
                created_at TEXT DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
                reacted_at TEXT DEFAULT NULL
            )"""
        )
        conn.execute(
            "ALTER TABLE IF EXISTS wishes_sent ADD COLUMN IF NOT EXISTS sender_digest_at TEXT DEFAULT NULL"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_wishes_recipient ON wishes_sent(recipient_id)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_wishes_sender ON wishes_sent(sender_id)"
        )


def get_or_create_user(telegram_id: int, username: str = None) -> int:
    """Возвращает id пользователя, создаёт если не существует."""
    with get_connection() as conn:
        row = conn.execute(
            """INSERT INTO users (telegram_id, username)
               VALUES (%s, %s)
               ON CONFLICT (telegram_id)
               DO UPDATE SET username = COALESCE(EXCLUDED.username, users.username)
               RETURNING id""",
            (telegram_id, username)
        ).fetchone()
        return row["id"]


def get_reminder_mode(telegram_id: int) -> str:
    """Возвращает режим напоминаний: once | repeat."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT reminder_mode FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return row["reminder_mode"] if row else "once"


def set_reminder_mode(telegram_id: int, mode: str, hours: int = None, minutes: int = 0):
    """Устанавливает режим напоминаний; опционально обновляет reminder_repeat_hours/minutes."""
    with get_connection() as conn:
        if hours is None:
            conn.execute(
                "UPDATE users SET reminder_mode = %s WHERE telegram_id = %s",
                (mode, telegram_id)
            )
        else:
            conn.execute(
                "UPDATE users SET reminder_mode = %s, reminder_repeat_hours = %s, reminder_repeat_minutes = %s WHERE telegram_id = %s",
                (mode, hours, minutes, telegram_id)
            )


def set_user_timezone(telegram_id: int, timezone: str):
    """Сохраняет часовой пояс пользователя."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET timezone = %s WHERE telegram_id = %s",
            (timezone, telegram_id)
        )


def get_user_timezone(telegram_id: int) -> str:
    """Возвращает часовой пояс пользователя."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT timezone FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return row["timezone"] if row else "UTC"


def get_user_time_presets(telegram_id: int) -> dict:
    """Возвращает пресеты времени пользователя {morning, lunch, evening, night}."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT time_morning, time_lunch, time_evening, time_night FROM users WHERE telegram_id = %s",
            (telegram_id,)
        ).fetchone()
        if row:
            return {
                "morning": row["time_morning"] or "09:00",
                "lunch":   row["time_lunch"]   or "12:00",
                "evening": row["time_evening"] or "18:00",
                "night":   row["time_night"]   or "22:00",
            }
        return {"morning": "09:00", "lunch": "12:00", "evening": "18:00", "night": "22:00"}


def set_user_time_preset(telegram_id: int, slot: str, time: str) -> int:
    """Обновляет пресет времени и переносит существующие правила с прежнего времени на новое.

    Слоты хранятся в schedule_rules как конкретное время (снимок пресета на момент
    создания). Чтобы смена пресета «прокидывалась» в напоминания/список/план, все
    активные правила пользователя с reminder_time == старое значение пресета
    обновляются на новое. Возвращает число обновлённых правил.
    """
    col_map = {"morning": "time_morning", "lunch": "time_lunch",
               "evening": "time_evening", "night": "time_night"}
    col = col_map.get(slot)
    if not col:
        raise ValueError(f"Unknown slot: {slot}")
    with get_connection() as conn:
        row = conn.execute(
            f"SELECT id, {col} AS old FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if row is None:
            return 0
        old_time, user_id = row["old"], row["id"]
        conn.execute(f"UPDATE users SET {col} = %s WHERE telegram_id = %s", (time, telegram_id))
        if not old_time or old_time == time:
            return 0
        cur = conn.execute(
            """UPDATE schedule_rules SET reminder_time = %s
               WHERE reminder_time = %s
                 AND medication_id IN (
                     SELECT id FROM medications WHERE user_id = %s AND active = 1
                 )""",
            (time, old_time, user_id)
        )
        return cur.rowcount


def count_active_medications(user_id: int, dependent_id: int = None) -> int:
    """Возвращает количество активных лекарств для user_id (dependent_id=None — для себя)."""
    with get_connection() as conn:
        if dependent_id is None:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM medications WHERE user_id = %s AND active = 1 AND dependent_id IS NULL",
                (user_id,)
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM medications WHERE user_id = %s AND active = 1 AND dependent_id = %s",
                (user_id, dependent_id)
            ).fetchone()
        return row["n"]


def get_caregiver_mode(telegram_id: int) -> bool:
    """Возвращает True если caregiver-режим включён."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT caregiver_enabled FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return bool(row["caregiver_enabled"]) if row else False


def set_caregiver_mode(telegram_id: int, enabled: bool):
    """Включает или выключает caregiver-режим."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET caregiver_enabled = %s WHERE telegram_id = %s",
            (1 if enabled else 0, telegram_id)
        )


# ── F7: caregiver_links ──────────────────────────────────────────────────────

def _count_total_dependents_conn(conn, telegram_id: int, user_id: int) -> int:
    """Суммарное число подопечных (локальные + активные linked). Принимает открытое соединение."""
    local = conn.execute(
        "SELECT COUNT(*) AS n FROM dependents WHERE user_id = %s", (user_id,)
    ).fetchone()["n"]
    linked = conn.execute(
        "SELECT COUNT(*) AS n FROM caregiver_links WHERE caregiver_id = %s AND status = 'active'",
        (user_id,)
    ).fetchone()["n"]
    return local + linked


def count_total_dependents(telegram_id: int) -> int:
    """Суммарное число подопечных пользователя (локальные + активные linked)."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return 0
        return _count_total_dependents_conn(conn, telegram_id, user["id"])


def ensure_caregiver_code(telegram_id: int) -> str:
    """Возвращает caregiver_code пользователя, генерирует при первом вызове."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT caregiver_code FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not row:
            raise DatabaseError("Пользователь не найден")
        if row["caregiver_code"]:
            return row["caregiver_code"]
        for _ in range(10):
            code = _gen_caregiver_code()
            updated = conn.execute(
                "UPDATE users SET caregiver_code = %s "
                "WHERE telegram_id = %s AND caregiver_code IS NULL RETURNING caregiver_code",
                (code, telegram_id)
            ).fetchone()
            if updated:
                return updated["caregiver_code"]
            row = conn.execute(
                "SELECT caregiver_code FROM users WHERE telegram_id = %s", (telegram_id,)
            ).fetchone()
            if row and row["caregiver_code"]:
                return row["caregiver_code"]
        raise DatabaseError("Не удалось сгенерировать уникальный код")


def create_caregiver_link(caregiver_telegram_id: int, code: str) -> dict:
    """Создаёт pending-запрос связи. Возвращает {id, dependent_telegram_id}."""
    with get_connection() as conn:
        caregiver = conn.execute(
            "SELECT id, username FROM users WHERE telegram_id = %s", (caregiver_telegram_id,)
        ).fetchone()
        if not caregiver:
            raise DatabaseError("Пользователь не найден")
        dependent = conn.execute(
            "SELECT id, telegram_id FROM users WHERE caregiver_code = %s", (code,)
        ).fetchone()
        if not dependent:
            raise DatabaseError("Код не найден")
        if dependent["id"] == caregiver["id"]:
            raise DatabaseError("Нельзя привязать себя")
        existing = conn.execute(
            "SELECT status FROM caregiver_links "
            "WHERE caregiver_id = %s AND dependent_id = %s AND status IN ('pending','active')",
            (caregiver["id"], dependent["id"])
        ).fetchone()
        if existing:
            raise DatabaseError("Запрос уже отправлен" if existing["status"] == "pending" else "Связь уже активна")
        row = conn.execute(
            "INSERT INTO caregiver_links (caregiver_id, dependent_id) VALUES (%s, %s) "
            "ON CONFLICT (caregiver_id, dependent_id) DO UPDATE "
            "SET status = 'pending', created_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') "
            "RETURNING id",
            (caregiver["id"], dependent["id"])
        ).fetchone()
        return {
            "id": row["id"],
            "dependent_telegram_id": dependent["telegram_id"],
            "caregiver_username": caregiver["username"],
        }


def confirm_caregiver_link(link_id: int, dependent_telegram_id: int) -> str:
    """Подтверждает pending-связь. Возвращает 'ok'|'limit'|'not_found'."""
    with get_connection() as conn:
        dep = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (dependent_telegram_id,)
        ).fetchone()
        if not dep:
            return "not_found"
        # F7-3.4: лимит 2 подопечных суммарно (local + active linked)
        total = _count_total_dependents_conn(conn, dependent_telegram_id, dep["id"])
        # Подопечный проверяет свой лимит как CAREGIVER (не как dependent)
        # На стороне ОПЕКУНА лимит — отдельная проверка в create_caregiver_link нет,
        # нужно проверить количество активных dependent у caregiver.
        # Находим caregiver_id для данной заявки
        link = conn.execute(
            "SELECT caregiver_id FROM caregiver_links WHERE id = %s AND dependent_id = %s AND status = 'pending'",
            (link_id, dep["id"])
        ).fetchone()
        if not link:
            return "not_found"
        caregiver_id = link["caregiver_id"]
        # Получаем telegram_id опекуна для проверки его лимита
        care_user = conn.execute(
            "SELECT telegram_id FROM users WHERE id = %s", (caregiver_id,)
        ).fetchone()
        care_total = _count_total_dependents_conn(conn, care_user["telegram_id"], caregiver_id)
        if care_total >= 2:
            return "limit"
        row = conn.execute(
            "UPDATE caregiver_links SET status = 'active' "
            "WHERE id = %s AND dependent_id = %s AND status = 'pending' RETURNING id",
            (link_id, dep["id"])
        ).fetchone()
        if not row:
            return "not_found"
        # F7-3.1: форсируем настройки подопечного: repeat 1ч + strict 1ч
        conn.execute(
            "UPDATE users SET reminder_mode='repeat', reminder_repeat_hours=1, "
            "strict_mode=1, strict_mode_hours=1 WHERE id = %s",
            (dep["id"],)
        )
        # Авто-включаем caregiver_enabled у опекуна при активации связи
        conn.execute(
            "UPDATE users SET caregiver_enabled = 1 WHERE id = %s",
            (caregiver_id,)
        )
        return "ok"


def decline_caregiver_link(link_id: int, dependent_telegram_id: int) -> bool:
    """Отклоняет pending-связь. Только подопечный может отклонить."""
    with get_connection() as conn:
        dep = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (dependent_telegram_id,)
        ).fetchone()
        if not dep:
            return False
        row = conn.execute(
            "UPDATE caregiver_links SET status = 'declined' "
            "WHERE id = %s AND dependent_id = %s AND status = 'pending' RETURNING id",
            (link_id, dep["id"])
        ).fetchone()
        return row is not None


def delete_caregiver_link(link_id: int, caregiver_telegram_id: int) -> bool:
    """Удаляет связь. Только опекун может разорвать."""
    with get_connection() as conn:
        caregiver = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (caregiver_telegram_id,)
        ).fetchone()
        if not caregiver:
            return False
        row = conn.execute(
            "DELETE FROM caregiver_links WHERE id = %s AND caregiver_id = %s RETURNING id",
            (link_id, caregiver["id"])
        ).fetchone()
        return row is not None


def request_caregiver_link_break(link_id: int, dependent_telegram_id: int) -> bool:
    """Подопечный запрашивает разрыв активной связи."""
    with get_connection() as conn:
        dep = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (dependent_telegram_id,)
        ).fetchone()
        if not dep:
            return False
        row = conn.execute(
            "UPDATE caregiver_links SET break_requested = 1 "
            "WHERE id = %s AND dependent_id = %s AND status = 'active' RETURNING id",
            (link_id, dep["id"])
        ).fetchone()
        return row is not None


def get_caregiver_links(telegram_id: int) -> dict:
    """Все связи пользователя: as_caregiver, as_dependent, pending_for_me."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return {"as_caregiver": [], "as_dependent": [], "pending_for_me": []}
        uid = user["id"]
        as_caregiver = conn.execute(
            "SELECT cl.id, cl.status, cl.created_at, cl.break_requested, "
            "u.id AS dependent_user_id, u.telegram_id AS dependent_telegram_id, u.username AS dependent_username, "
            "u.reminder_mode, u.reminder_repeat_hours, u.strict_mode, u.strict_mode_hours "
            "FROM caregiver_links cl JOIN users u ON u.id = cl.dependent_id "
            "WHERE cl.caregiver_id = %s AND cl.status IN ('pending','active') ORDER BY cl.id",
            (uid,)
        ).fetchall()
        as_dependent = conn.execute(
            "SELECT cl.id, cl.status, cl.created_at, cl.break_requested, "
            "u.telegram_id AS caregiver_telegram_id, u.username AS caregiver_username "
            "FROM caregiver_links cl JOIN users u ON u.id = cl.caregiver_id "
            "WHERE cl.dependent_id = %s AND cl.status IN ('pending','active') ORDER BY cl.id",
            (uid,)
        ).fetchall()
        pending = [dict(r) for r in as_dependent if r["status"] == "pending"]
        active_care = next((dict(r) for r in as_dependent if r["status"] == "active"), None)
        return {
            "as_caregiver": [dict(r) for r in as_caregiver],
            "as_dependent": [dict(r) for r in as_dependent],
            "pending_for_me": pending,
            "active_caregiver": active_care,
        }


def get_caregiver_link_parties(link_id: int) -> dict | None:
    """Telegram-id и username обеих сторон связи. Для уведомлений (10-A/10-B)."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT cl.status, "
            "c.telegram_id AS caregiver_telegram_id, c.username AS caregiver_username, "
            "d.telegram_id AS dependent_telegram_id, d.username AS dependent_username "
            "FROM caregiver_links cl "
            "JOIN users c ON c.id = cl.caregiver_id "
            "JOIN users d ON d.id = cl.dependent_id "
            "WHERE cl.id = %s",
            (link_id,)
        ).fetchone()
        return dict(row) if row else None


def get_dep_share_parties(share_id: int) -> dict | None:
    """Telegram-id и username владельца + наблюдателя + имя близкого. Для уведомлений."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT ds.status, dep.name AS dep_name, "
            "o.telegram_id AS owner_telegram_id, o.username AS owner_username, "
            "v.telegram_id AS viewer_telegram_id, v.username AS viewer_username "
            "FROM dependent_shares ds "
            "JOIN users o ON o.id = ds.owner_user_id "
            "JOIN users v ON v.id = ds.viewer_user_id "
            "JOIN dependents dep ON dep.id = ds.dep_id "
            "WHERE ds.id = %s",
            (share_id,)
        ).fetchone()
        return dict(row) if row else None


def is_active_dependent(telegram_id: int) -> bool:
    """True если пользователь — подопечный с активной связью (для блокировки настроек)."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return False
        row = conn.execute(
            "SELECT 1 FROM caregiver_links WHERE dependent_id = %s AND status = 'active' LIMIT 1",
            (user["id"],)
        ).fetchone()
        return row is not None


def get_caregiver_tids_for_dependent(dependent_user_id: int) -> list:
    """F10-C: telegram_id всех активных опекунов подопечного (для пуша о пропуске)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT c.telegram_id FROM caregiver_links cl "
            "JOIN users c ON c.id = cl.caregiver_id "
            "WHERE cl.dependent_id = %s AND cl.status = 'active'",
            (dependent_user_id,)
        ).fetchall()
        return [r["telegram_id"] for r in rows]


def get_dep_share_viewer_tids(dep_id: int) -> list:
    """F10-C: telegram_id активных наблюдателей локального близкого (для пуша о пропуске)."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT v.telegram_id FROM dependent_shares ds "
            "JOIN users v ON v.id = ds.viewer_user_id "
            "WHERE ds.dep_id = %s AND ds.status = 'active'",
            (dep_id,)
        ).fetchall()
        return [r["telegram_id"] for r in rows]


def get_linked_dependents_for_caregiver(caregiver_telegram_id: int) -> list:
    """Возвращает [{user_id, telegram_id, username}] активных подопечных опекуна.
    Возвращает пустой список если caregiver_enabled = 0 (режим выключен)."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id, caregiver_enabled FROM users WHERE telegram_id = %s",
            (caregiver_telegram_id,)
        ).fetchone()
        if not user or not user["caregiver_enabled"]:
            return []
        return conn.execute(
            "SELECT u.id AS user_id, u.telegram_id, u.username "
            "FROM caregiver_links cl JOIN users u ON u.id = cl.dependent_id "
            "WHERE cl.caregiver_id = %s AND cl.status = 'active'",
            (user["id"],)
        ).fetchall()


def is_caregiver_for_user_id(caregiver_telegram_id: int, dependent_user_id: int) -> bool:
    """True если у пользователя есть активная связь как опекун с данным dependent_user_id."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (caregiver_telegram_id,)
        ).fetchone()
        if not user:
            return False
        row = conn.execute(
            "SELECT 1 FROM caregiver_links "
            "WHERE caregiver_id = %s AND dependent_id = %s AND status = 'active'",
            (user["id"], dependent_user_id)
        ).fetchone()
        return row is not None


def set_dependent_settings(
    caregiver_telegram_id: int,
    link_id: int,
    reminder_mode: str = None,
    reminder_hours: int = None,
    reminder_minutes: int = None,
    strict_mode: bool = None,
    strict_hours: int = None,
    strict_minutes: int = None,
) -> bool:
    """Опекун меняет настройки подопечного. True если нашёл активную связь."""
    with get_connection() as conn:
        care_user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (caregiver_telegram_id,)
        ).fetchone()
        if not care_user:
            return False
        link = conn.execute(
            "SELECT dependent_id FROM caregiver_links "
            "WHERE id = %s AND caregiver_id = %s AND status = 'active'",
            (link_id, care_user["id"])
        ).fetchone()
        if not link:
            return False
        dep_id = link["dependent_id"]
        if reminder_mode is not None:
            if reminder_hours is not None:
                conn.execute(
                    "UPDATE users SET reminder_mode = %s, reminder_repeat_hours = %s, reminder_repeat_minutes = %s WHERE id = %s",
                    (reminder_mode, reminder_hours, reminder_minutes or 0, dep_id),
                )
            else:
                conn.execute(
                    "UPDATE users SET reminder_mode = %s WHERE id = %s",
                    (reminder_mode, dep_id),
                )
        if strict_mode is not None:
            if strict_hours is not None:
                conn.execute(
                    "UPDATE users SET strict_mode = %s, strict_mode_hours = %s, strict_mode_minutes = %s WHERE id = %s",
                    (1 if strict_mode else 0, strict_hours, strict_minutes or 0, dep_id),
                )
            else:
                conn.execute(
                    "UPDATE users SET strict_mode = %s WHERE id = %s",
                    (1 if strict_mode else 0, dep_id),
                )
        return True


# ── F8: dependent_shares ─────────────────────────────────────────────────────

def _gen_dep_share_code() -> str:
    c = "".join(secrets.choice(_CODE_CHARS) for _ in range(12))
    return f"{c[:4]}-{c[4:8]}-{c[8:]}"


def ensure_dep_share_code(dep_id: int, owner_telegram_id: int) -> str:
    """Возвращает share_code для близкого, генерирует при первом вызове. Проверяет владельца."""
    with get_connection() as conn:
        dep = conn.execute(
            "SELECT d.id, d.share_code FROM dependents d "
            "JOIN users u ON u.id = d.user_id "
            "WHERE d.id = %s AND u.telegram_id = %s",
            (dep_id, owner_telegram_id)
        ).fetchone()
        if not dep:
            raise DatabaseError("Близкий не найден")
        if dep["share_code"]:
            return dep["share_code"]
        for _ in range(10):
            code = _gen_dep_share_code()
            updated = conn.execute(
                "UPDATE dependents SET share_code = %s "
                "WHERE id = %s AND share_code IS NULL RETURNING share_code",
                (code, dep_id)
            ).fetchone()
            if updated:
                return updated["share_code"]
            row = conn.execute("SELECT share_code FROM dependents WHERE id = %s", (dep_id,)).fetchone()
            if row and row["share_code"]:
                return row["share_code"]
        raise DatabaseError("Не удалось сгенерировать уникальный код")


def request_dep_share(viewer_telegram_id: int, code: str) -> dict:
    """Создаёт pending-запрос на наблюдение. Возвращает {share_id, dep_name, owner_telegram_id}."""
    with get_connection() as conn:
        dep = conn.execute(
            "SELECT d.id, d.name, u.id AS owner_user_id, u.telegram_id AS owner_telegram_id "
            "FROM dependents d JOIN users u ON u.id = d.user_id "
            "WHERE d.share_code = %s",
            (code,)
        ).fetchone()
        if not dep:
            raise DatabaseError("Код не найден")
        viewer = conn.execute(
            "SELECT id, username FROM users WHERE telegram_id = %s", (viewer_telegram_id,)
        ).fetchone()
        if not viewer:
            raise DatabaseError("Пользователь не найден")
        if viewer["id"] == dep["owner_user_id"]:
            raise DatabaseError("Нельзя наблюдать за собственным близким")
        existing = conn.execute(
            "SELECT status FROM dependent_shares WHERE dep_id = %s AND viewer_user_id = %s",
            (dep["id"], viewer["id"])
        ).fetchone()
        if existing and existing["status"] == "active":
            raise DatabaseError("Уже наблюдаете за этим близким")
        active_count = conn.execute(
            "SELECT COUNT(*) AS n FROM dependent_shares WHERE dep_id = %s AND status = 'active'",
            (dep["id"],)
        ).fetchone()["n"]
        if active_count >= 1:
            raise DatabaseError("Достигнут лимит наблюдателей (1)")
        share = conn.execute(
            """INSERT INTO dependent_shares (dep_id, owner_user_id, viewer_user_id, status)
               VALUES (%s, %s, %s, 'pending')
               ON CONFLICT (dep_id, viewer_user_id)
               DO UPDATE SET status = 'pending'
               RETURNING id""",
            (dep["id"], dep["owner_user_id"], viewer["id"])
        ).fetchone()
        return {
            "share_id": share["id"],
            "dep_name": dep["name"],
            "owner_telegram_id": dep["owner_telegram_id"],
            "viewer_username": viewer["username"],
        }


def confirm_dep_share(share_id: int, owner_telegram_id: int) -> dict:
    """Подтверждает запрос. Возвращает {viewer_telegram_id, dep_name}."""
    with get_connection() as conn:
        owner = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (owner_telegram_id,)
        ).fetchone()
        if not owner:
            raise DatabaseError("Пользователь не найден")
        active_count = conn.execute(
            """SELECT COUNT(*) AS n FROM dependent_shares ds
               JOIN dependent_shares s2 ON s2.dep_id = ds.dep_id
               WHERE ds.id = %s AND ds.owner_user_id = %s AND s2.status = 'active'""",
            (share_id, owner["id"])
        ).fetchone()["n"]
        if active_count >= 1:
            raise DatabaseError("Достигнут лимит наблюдателей (1)")
        row = conn.execute(
            """UPDATE dependent_shares SET status = 'active'
               WHERE id = %s AND owner_user_id = %s AND status = 'pending'
               RETURNING dep_id, viewer_user_id""",
            (share_id, owner["id"])
        ).fetchone()
        if not row:
            raise DatabaseError("Запрос не найден")
        viewer = conn.execute(
            "SELECT telegram_id FROM users WHERE id = %s", (row["viewer_user_id"],)
        ).fetchone()
        dep = conn.execute("SELECT name FROM dependents WHERE id = %s", (row["dep_id"],)).fetchone()
        return {
            "viewer_telegram_id": viewer["telegram_id"] if viewer else None,
            "dep_name": dep["name"] if dep else "",
        }


def decline_dep_share(share_id: int, owner_telegram_id: int) -> bool:
    with get_connection() as conn:
        owner = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (owner_telegram_id,)
        ).fetchone()
        if not owner:
            return False
        row = conn.execute(
            "DELETE FROM dependent_shares WHERE id = %s AND owner_user_id = %s AND status = 'pending' RETURNING id",
            (share_id, owner["id"])
        ).fetchone()
        return row is not None


def revoke_dep_share(share_id: int, owner_telegram_id: int) -> bool:
    with get_connection() as conn:
        owner = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (owner_telegram_id,)
        ).fetchone()
        if not owner:
            return False
        row = conn.execute(
            "DELETE FROM dependent_shares WHERE id = %s AND owner_user_id = %s RETURNING id",
            (share_id, owner["id"])
        ).fetchone()
        return row is not None


def leave_dep_share(share_id: int, viewer_telegram_id: int) -> bool:
    """Viewer сам отписывается."""
    with get_connection() as conn:
        viewer = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (viewer_telegram_id,)
        ).fetchone()
        if not viewer:
            return False
        row = conn.execute(
            "DELETE FROM dependent_shares WHERE id = %s AND viewer_user_id = %s RETURNING id",
            (share_id, viewer["id"])
        ).fetchone()
        return row is not None


def get_dep_shares_for_owner(owner_telegram_id: int) -> dict:
    """Возвращает {dep_id: {share_code, active_viewer, pending_viewers}} для всех локальных близких."""
    with get_connection() as conn:
        owner = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (owner_telegram_id,)
        ).fetchone()
        if not owner:
            return {}
        deps = conn.execute(
            "SELECT id, name, share_code FROM dependents WHERE user_id = %s",
            (owner["id"],)
        ).fetchall()
        result = {}
        for dep in deps:
            shares = conn.execute(
                """SELECT ds.id AS share_id, ds.status, u.username, u.telegram_id
                   FROM dependent_shares ds JOIN users u ON u.id = ds.viewer_user_id
                   WHERE ds.dep_id = %s AND ds.status IN ('pending', 'active')
                   ORDER BY ds.id""",
                (dep["id"],)
            ).fetchall()
            active = next((s for s in shares if s["status"] == "active"), None)
            pending = [s for s in shares if s["status"] == "pending"]
            result[dep["id"]] = {
                "share_code": dep["share_code"],
                "active_viewer": {
                    "share_id": active["share_id"],
                    "username": active["username"] or f"id{active['telegram_id']}",
                } if active else None,
                "pending_viewers": [
                    {"share_id": s["share_id"], "username": s["username"] or f"id{s['telegram_id']}"}
                    for s in pending
                ],
            }
        return result


def get_shared_deps_for_viewer(viewer_telegram_id: int) -> list:
    """Возвращает список близких, за которыми наблюдает viewer."""
    with get_connection() as conn:
        viewer = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (viewer_telegram_id,)
        ).fetchone()
        if not viewer:
            return []
        return conn.execute(
            """SELECT ds.id AS share_id, d.id AS dep_id, d.name AS dep_name,
                      u.telegram_id AS owner_telegram_id, u.username AS owner_username
               FROM dependent_shares ds
               JOIN dependents d ON d.id = ds.dep_id
               JOIN users u ON u.id = ds.owner_user_id
               WHERE ds.viewer_user_id = %s AND ds.status = 'active'""",
            (viewer["id"],)
        ).fetchall()


def get_viewer_shared_deps(user_id: int) -> list:
    """Возвращает [{dep_id, share_id, dep_name, owner_user_id}] для активных viewer-shares."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT ds.id AS share_id, ds.dep_id, d.name AS dep_name, d.user_id AS owner_user_id
               FROM dependent_shares ds
               JOIN dependents d ON d.id = ds.dep_id
               WHERE ds.viewer_user_id = %s AND ds.status = 'active'""",
            (user_id,)
        ).fetchall()
        return [dict(r) for r in rows]


def get_medications_for_dep(dep_id: int) -> list:
    """Возвращает активные лекарства конкретного локального близкого."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT * FROM medications WHERE dependent_id = %s AND active = 1",
            (dep_id,)
        ).fetchall()


def get_rules_grouped_for_dep(dep_id: int) -> dict:
    """Возвращает {medication_id: [rules]} для всех активных лекарств близкого."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT sr.medication_id, sr.reminder_time, sr.frequency,
                      sr.interval_days, sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage, sr.dose_cycle
               FROM schedule_rules sr
               JOIN medications m ON m.id = sr.medication_id
               WHERE m.dependent_id = %s AND m.active = 1
               ORDER BY sr.medication_id""",
            (dep_id,)
        ).fetchall()
    grouped: dict = {}
    for r in rows:
        grouped.setdefault(r["medication_id"], []).append(r)
    return grouped


def get_medication_by_id_raw(med_id: int):
    """Возвращает лекарство по id без фильтрации по user_id."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT * FROM medications WHERE id = %s", (med_id,)
        ).fetchone()


def get_telegram_id_by_user_id(user_id: int):
    """Возвращает telegram_id по внутреннему user_id (или None)."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT telegram_id FROM users WHERE id = %s", (user_id,)
        ).fetchone()
        return row["telegram_id"] if row else None


def get_dep_share_viewer_ids(dep_id: int) -> list:
    """user_id всех активных помощников (viewer) данного локального близкого."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT viewer_user_id FROM dependent_shares "
            "WHERE dep_id = %s AND status = 'active'",
            (dep_id,)
        ).fetchall()
        return [r["viewer_user_id"] for r in rows]


def transfer_dep_to_viewer(telegram_id: int, dep_id: int) -> bool:
    """Передаёт владение близким активному viewer. Возвращает True если передано."""
    with get_connection() as conn:
        owner = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not owner:
            return False
        share = conn.execute(
            "SELECT id, viewer_user_id FROM dependent_shares "
            "WHERE dep_id = %s AND owner_user_id = %s AND status = 'active'",
            (dep_id, owner["id"])
        ).fetchone()
        if not share:
            return False
        viewer_uid = share["viewer_user_id"]
        conn.execute("UPDATE dependents SET user_id = %s WHERE id = %s", (viewer_uid, dep_id))
        conn.execute(
            "UPDATE medications SET user_id = %s WHERE dependent_id = %s",
            (viewer_uid, dep_id)
        )
        conn.execute("DELETE FROM dependent_shares WHERE id = %s", (share["id"],))
        return True


def get_pending_viewing_deps(viewer_telegram_id: int) -> list:
    """Возвращает pending-заявки где текущий пользователь — viewer."""
    with get_connection() as conn:
        viewer = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (viewer_telegram_id,)
        ).fetchone()
        if not viewer:
            return []
        return conn.execute(
            """SELECT ds.id AS share_id, d.name AS dep_name,
                      u.username AS owner_username, u.telegram_id AS owner_telegram_id
               FROM dependent_shares ds
               JOIN dependents d ON d.id = ds.dep_id
               JOIN users u ON u.id = ds.owner_user_id
               WHERE ds.viewer_user_id = %s AND ds.status = 'pending'""",
            (viewer["id"],)
        ).fetchall()


def get_schedules_for_dependent(dep_id: int) -> list:
    """Возвращает активные правила расписания для конкретного локального близкого."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT u.telegram_id, u.timezone,
                      m.id AS medication_id, m.name, m.dosage AS med_dosage, m.meal_relation,
                      m.unit_dose_value, m.unit_dose_label,
                      sr.reminder_time, sr.frequency, sr.interval_days,
                      sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage AS rule_dosage, sr.dose_cycle,
                      d.name AS dependent_name
               FROM dependents d
               JOIN users u ON u.id = d.user_id
               JOIN medications m ON m.user_id = u.id AND m.dependent_id = d.id AND m.active = 1
               JOIN schedule_rules sr ON sr.medication_id = m.id
               WHERE d.id = %s AND m.paused = 0
               ORDER BY m.id, sr.reminder_time""",
            (dep_id,)
        ).fetchall()


def get_today_intake_statuses_for_dep(dep_id: int, start_utc: str, end_utc: str) -> dict:
    """Статусы приёмов для конкретного локального близкого за день."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT i.medication_id, i.scheduled_time, i.status
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.dependent_id = %s AND i.taken_at >= %s AND i.taken_at < %s""",
            (dep_id, start_utc, end_utc)
        ).fetchall()
    return {(r["medication_id"], r["scheduled_time"]): r["status"] for r in rows}


def get_medication_by_id_any_user(medication_id: int, user_ids: list):
    """Возвращает лекарство если оно принадлежит любому из user_ids."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT * FROM medications WHERE id = %s AND user_id = ANY(%s)",
            (medication_id, user_ids)
        ).fetchone()


def get_dependents(telegram_id: int) -> list:
    """Возвращает список подопечных пользователя [{id, name}, ...]."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return []
        return conn.execute(
            "SELECT id, name FROM dependents WHERE user_id = %s ORDER BY id",
            (user["id"],)
        ).fetchall()


def count_dependents(telegram_id: int) -> int:
    """Возвращает количество подопечных пользователя."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return 0
        return conn.execute(
            "SELECT COUNT(*) AS n FROM dependents WHERE user_id = %s", (user["id"],)
        ).fetchone()["n"]


def add_dependent(telegram_id: int, name: str) -> int:
    """Добавляет подопечного. Возвращает id новой записи."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            raise DatabaseError("Пользователь не найден")
        row = conn.execute(
            "INSERT INTO dependents (user_id, name) VALUES (%s, %s) RETURNING id",
            (user["id"], name)
        ).fetchone()
        return row["id"]


def delete_dependent(telegram_id: int, dependent_id: int) -> list:
    """Удаляет подопечного и деактивирует его лекарства. Возвращает список ID лекарств."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return []
        user_id = user["id"]
        dep = conn.execute(
            "SELECT id FROM dependents WHERE id = %s AND user_id = %s", (dependent_id, user_id)
        ).fetchone()
        if not dep:
            return []
        med_ids = [r["id"] for r in conn.execute(
            "SELECT id FROM medications WHERE user_id = %s AND dependent_id = %s",
            (user_id, dependent_id)
        ).fetchall()]
        if med_ids:
            conn.execute("DELETE FROM intake_log WHERE medication_id = ANY(%s)", (med_ids,))
            conn.execute("DELETE FROM schedule_rules WHERE medication_id = ANY(%s)", (med_ids,))
            # dependent_id = NULL обязательно: иначе DELETE подопечного нарушит FK
            conn.execute(
                "UPDATE medications SET active = 0, dependent_id = NULL WHERE dependent_id = %s AND user_id = %s",
                (dependent_id, user_id)
            )
        conn.execute("DELETE FROM dependents WHERE id = %s", (dependent_id,))
        return med_ids


def _parse_dose_number(s):
    """Число из строки дозы правила ("250 мг" → 250.0). None если не распарсить."""
    if not s:
        return None
    import re
    m = re.match(r"\s*([\d.,]+)", str(s))
    if not m:
        return None
    try:
        return float(m.group(1).replace(",", "."))
    except ValueError:
        return None


def compute_units_per_dose(dose_per_intake, unit_dose_value) -> float:
    """Сколько единиц упаковки списывать за приём = назначено / дозировка 1 ед.

    Аспирин 500 мг/таб, назначено 250 мг → 250/500 = 0.5 таб. Если структурных
    данных нет (свободная дозировка строкой) — 1 единица за приём (как раньше).
    """
    if dose_per_intake and unit_dose_value and unit_dose_value > 0:
        return dose_per_intake / unit_dose_value
    return 1


def add_medication(user_id: int, name: str, dosage: str,
                   meal_relation: str, times_per_day: int,
                   dependent_id: int = None, *,
                   unit_dose_value=None, unit_dose_label: str = "мг",
                   dose_per_intake=None, pack_size=None,
                   course_total=None) -> int:
    """Добавляет лекарство и возвращает его id.

    Новая модель: упаковка задаётся через unit_dose_value (дозировка 1 ед.),
    pack_size (ед. в упаковке → стартовый остаток), dose_per_intake (назначено
    за приём). units_per_dose считается на сервере. pack_size None → учёт запаса
    выключен (stock_qty NULL)."""
    units_per_dose = compute_units_per_dose(dose_per_intake, unit_dose_value)
    stock_qty = pack_size if pack_size is not None else None
    with get_connection() as conn:
        row = conn.execute(
            """INSERT INTO medications
               (user_id, name, dosage, meal_relation, times_per_day, dependent_id,
                unit_dose_value, unit_dose_label, dose_per_intake, pack_size,
                course_total, units_per_dose, stock_qty)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
               RETURNING id""",
            (user_id, name, dosage, meal_relation, times_per_day, dependent_id,
             unit_dose_value, unit_dose_label, dose_per_intake, pack_size,
             course_total, units_per_dose, stock_qty)
        ).fetchone()
        return row["id"]


def add_schedule(medication_id: int, reminder_time: str):
    """Добавляет ежедневное напоминание (обратная совместимость)."""
    add_schedule_rule(medication_id, reminder_time, "daily")


def create_demo_medication(user_id: int) -> int | None:
    """Онбординг: создаёт демо-препарат «Счастьепин» новому юзеру, чтобы туру было
    что показать (карточка приёма + расписание). Идемпотентно: если у юзера уже
    есть активные лекарства — ничего не делает и возвращает None."""
    with get_connection() as conn:
        existing = conn.execute(
            "SELECT 1 FROM medications WHERE user_id = %s AND active = 1 LIMIT 1",
            (user_id,)
        ).fetchone()
        if existing:
            return None
    med_id = add_medication(
        user_id, "Счастьепин", "1 таблетка", "after", 1,
    )
    add_schedule_rule(med_id, "09:00", "daily")
    return med_id


def add_schedule_rule(medication_id: int, reminder_time: str, frequency: str,
                      interval_days: int = None, weekdays: str = None,
                      month_day: int = None, anchor_date: str = None, dosage: str = None,
                      dose_cycle: str = None):
    """Добавляет правило напоминания в schedule_rules."""
    with get_connection() as conn:
        conn.execute(
            """INSERT INTO schedule_rules
               (medication_id, reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage, dose_cycle)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (medication_id, reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage, dose_cycle)
        )


def get_user_medications(user_id: int) -> list:
    """Возвращает активные лекарства пользователя с именем подопечного."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.*, d.name AS dependent_name
               FROM medications m
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.user_id = %s AND m.active = 1
               ORDER BY m.id""",
            (user_id,)
        ).fetchall()


# AX11: общие SQL-фрагменты выборки правил расписания (устранение дублей).
# Список rule-колонок одинаков во всех трёх выборках (порядок важен — потребители
# читают по ключам, но держим единый источник истины).
_RULE_COLS = (
    "sr.reminder_time, sr.frequency, sr.interval_days, "
    "sr.weekdays, sr.month_day, sr.anchor_date, sr.dose_cycle"
)
# Ядро per-user выборок (adherence F3 / streak F2): идентичный JOIN, фильтр, ORDER.
_USER_RULES_FROM = (
    "FROM medications m "
    "JOIN schedule_rules sr ON sr.medication_id = m.id "
    "LEFT JOIN dependents d ON d.id = m.dependent_id "
    "WHERE m.user_id = %s AND m.active = 1 AND m.paused = 0 "
    "ORDER BY m.id"
)


def get_active_schedule_rows() -> list:
    """Все правила расписания активных лекарств + поля пользователя — один проход.

    Покрывает и напоминания (reminder_mode), и план дня (daily_plan_enabled /
    daily_plan_time). Фильтрация по плану дня выполняется в Python, без второго запроса.
    Собственный FROM (JOIN users, без фильтра по user_id, свой ORDER) — горячий путь
    планировщика, не сливаем с per-user выборками; общий только список rule-колонок.
    """
    with get_connection() as conn:
        return conn.execute(
            f"""SELECT u.telegram_id, u.id AS user_id, u.username AS owner_username,
                      u.timezone, u.reminder_mode,
                      u.daily_plan_enabled, u.daily_plan_time,
                      u.strict_mode, u.strict_mode_hours, u.strict_mode_minutes,
                      u.reminder_repeat_hours, u.reminder_repeat_minutes,
                      m.id AS medication_id, m.name, m.dosage AS med_dosage, m.meal_relation,
                      m.dependent_id AS dependent_id, m.unit_dose_value, m.unit_dose_label,
                      {_RULE_COLS}, sr.dosage AS rule_dosage,
                      d.name AS dependent_name
               FROM schedule_rules sr
               JOIN medications m ON m.id = sr.medication_id
               JOIN users u ON u.id = m.user_id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.active = 1 AND m.paused = 0
               ORDER BY u.telegram_id, m.id, sr.reminder_time"""
        ).fetchall()


def deactivate_medication(medication_id: int, user_id: int):
    """Деактивирует лекарство и удаляет его расписание."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET active = 0 WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        )
        conn.execute(
            "DELETE FROM schedule_rules WHERE medication_id = %s",
            (medication_id,)
        )


def get_today_stats(user_id: int, start_utc: str, end_utc: str) -> list:
    """Возвращает статистику приёмов за сегодня (диапазон в UTC)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name, m.dosage, i.scheduled_time, i.status, i.taken_at
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s AND i.taken_at < %s
               ORDER BY i.taken_at""",
            (user_id, start_utc, end_utc)
        ).fetchall()


def get_history_detailed(user_id: int, since_utc: str) -> list:
    """Возвращает детальную историю начиная с since_utc (UTC строка)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name, m.dosage, m.id as med_id,
                      i.scheduled_time, i.status, i.taken_at,
                      d.name AS dependent_name
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s
               ORDER BY i.taken_at DESC, m.name, i.scheduled_time""",
            (user_id, since_utc)
        ).fetchall()


def get_history_by_days(user_id: int, days: int = 7) -> list:
    """Возвращает статистику по дням для каждого лекарства."""
    since = (datetime.now(timezone.utc) - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name, m.dosage,
                      LEFT(i.taken_at, 10) AS day,
                      SUM(CASE WHEN i.status = 'taken' THEN 1 ELSE 0 END) AS taken,
                      SUM(CASE WHEN i.status = 'skipped' THEN 1 ELSE 0 END) AS skipped,
                      COUNT(*) AS total
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s
               GROUP BY m.id, m.name, LEFT(i.taken_at, 10)
               ORDER BY m.name, day DESC""",
            (user_id, since)
        ).fetchall()


def get_history(user_id: int, days: int = 7) -> list:
    """Возвращает статистику приёмов за последние N дней."""
    since = (datetime.now(timezone.utc) - timedelta(days=days)).strftime('%Y-%m-%d %H:%M:%S')
    with get_connection() as conn:
        return conn.execute(
            """SELECT m.name,
                      COUNT(*) AS total,
                      SUM(CASE WHEN i.status = 'taken' THEN 1 ELSE 0 END) AS taken,
                      SUM(CASE WHEN i.status = 'skipped' THEN 1 ELSE 0 END) AS skipped
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s
               AND i.taken_at >= %s
               GROUP BY m.id, m.name
               ORDER BY m.name""",
            (user_id, since)
        ).fetchall()


def set_medication_paused(medication_id: int, user_id: int, paused: bool):
    """Ставит лекарство на паузу / снимает с паузы (F4)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET paused = %s WHERE id = %s AND user_id = %s",
            (1 if paused else 0, medication_id, user_id)
        )


def get_medication_by_id(medication_id: int, user_id: int):
    """Возвращает лекарство по id."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT * FROM medications WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        ).fetchone()


def get_schedules_by_medication(medication_id: int) -> list:
    """Возвращает правила расписания для лекарства."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage, dose_cycle
               FROM schedule_rules WHERE medication_id = %s""",
            (medication_id,)
        ).fetchall()


def get_rules_grouped_for_user(user_id: int) -> dict:
    """Возвращает {medication_id: [rule, ...]} для всех активных лекарств пользователя одним запросом."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT sr.medication_id, sr.reminder_time, sr.frequency,
                      sr.interval_days, sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage, sr.dose_cycle
               FROM schedule_rules sr
               JOIN medications m ON m.id = sr.medication_id
               WHERE m.user_id = %s AND m.active = 1
               ORDER BY sr.medication_id""",
            (user_id,)
        ).fetchall()
    grouped: dict = {}
    for r in rows:
        grouped.setdefault(r["medication_id"], []).append(r)
    return grouped


# ── Соблюдение режима / adherence (F3) ──────────────────────────────────────

def get_adherence_rules(user_id: int) -> list:
    """Правила активных лекарств пользователя + created_at/имя/подопечный (F3)."""
    with get_connection() as conn:
        return conn.execute(
            f"""SELECT m.id AS medication_id, m.name, m.dosage AS med_dosage,
                      m.created_at, d.name AS dependent_name,
                      {_RULE_COLS}
               {_USER_RULES_FROM}""",
            (user_id,)
        ).fetchall()


def get_taken_intakes(user_id: int, start_utc: str, end_utc: str) -> list:
    """(medication_id, taken_at) для status='taken' в окне — для календаря отчёта врача (F1)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT i.medication_id AS mid, i.taken_at
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s AND i.status = 'taken'
                 AND i.taken_at >= %s AND i.taken_at < %s""",
            (user_id, start_utc, end_utc)
        ).fetchall()


def get_taken_counts(user_id: int, start_utc: str, end_utc: str) -> dict:
    """{medication_id: число приёмов status='taken' за [start_utc, end_utc)} — числитель adherence (F3)."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT i.medication_id AS mid, COUNT(*) AS cnt
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s AND i.status = 'taken'
                 AND i.taken_at >= %s AND i.taken_at < %s
               GROUP BY i.medication_id""",
            (user_id, start_utc, end_utc)
        ).fetchall()
    return {r["mid"]: r["cnt"] for r in rows}


def get_course_progress(medication_id: int) -> int:
    """Сколько приёмов лекарства уже отмечено 'taken' за всё время (прогресс курса).

    Курс завершён, когда это значение ≥ medications.course_total (вычисляется
    в API/фронте; флага в БД нет)."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT COUNT(*) AS cnt FROM intake_log WHERE medication_id = %s AND status = 'taken'",
            (medication_id,)
        ).fetchone()
        return row["cnt"] if row else 0


def get_streak_rows(user_id: int) -> list:
    """Правила активных непаузных лекарств + dependent_id/имя/created_at — для серий (F2)."""
    with get_connection() as conn:
        return conn.execute(
            f"""SELECT m.id AS medication_id, m.dependent_id, m.created_at,
                      d.name AS dependent_name,
                      {_RULE_COLS}
               {_USER_RULES_FROM}""",
            (user_id,)
        ).fetchall()


def get_own_meds_units(user_id: int) -> dict:
    """{medication_id: units_per_dose} для активных непаузных СОБСТВЕННЫХ лекарств (F11-C).

    dependent_id IS NULL — без лекарств локальных близких. Для расчёта нагрузки терапии.
    """
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT id, units_per_dose FROM medications "
            "WHERE user_id = %s AND active = 1 AND paused = 0 AND dependent_id IS NULL",
            (user_id,)
        ).fetchall()
    return {r["id"]: r["units_per_dose"] for r in rows}


def get_intake_statuses_window(user_id: int, start_utc: str, end_utc: str) -> list:
    """Записи intake_log (mid, scheduled_time, status, taken_at) пользователя за окно — для серий (F2)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT i.medication_id, i.scheduled_time, i.status, i.taken_at
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE m.user_id = %s AND i.taken_at >= %s AND i.taken_at < %s""",
            (user_id, start_utc, end_utc)
        ).fetchall()


def update_medication(medication_id: int, user_id: int, name: str, dosage: str,
                      meal_relation: str, times_per_day: int, new_rules: list, *,
                      unit_dose_value=None, unit_dose_label: str = "мг",
                      dose_per_intake=None, pack_size=None, course_total=None):
    """Обновляет лекарство и его расписание. new_rules — список dict с полями rule.

    Пересчитывает units_per_dose. «Ед. в упаковке» (pack_size) теперь = текущий
    запас: stock_qty синхронизируется с pack_size (единый источник для пользователя;
    отдельной панели «учёт запаса» больше нет). pack_size=None → учёт выключён."""
    units_per_dose = compute_units_per_dose(dose_per_intake, unit_dose_value)
    with get_connection() as conn:
        conn.execute(
            """UPDATE medications SET name=%s, dosage=%s, meal_relation=%s, times_per_day=%s,
                   unit_dose_value=%s, unit_dose_label=%s, dose_per_intake=%s,
                   pack_size=%s, stock_qty=%s, course_total=%s, units_per_dose=%s
               WHERE id=%s AND user_id=%s""",
            (name, dosage, meal_relation, times_per_day,
             unit_dose_value, unit_dose_label, dose_per_intake, pack_size,
             pack_size, course_total, units_per_dose, medication_id, user_id)
        )
        conn.execute("DELETE FROM schedule_rules WHERE medication_id=%s", (medication_id,))
        for rule in new_rules:
            conn.execute(
                """INSERT INTO schedule_rules
                   (medication_id, reminder_time, frequency, interval_days, weekdays, month_day, anchor_date, dosage, dose_cycle)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                (medication_id, rule["reminder_time"], rule.get("frequency", "daily"),
                 rule.get("interval_days"), rule.get("weekdays"),
                 rule.get("month_day"), rule.get("anchor_date"), rule.get("dosage"),
                 rule.get("dose_cycle"))
            )


def get_user_settings_row(telegram_id: int):
    """Возвращает строку настроек пользователя одним запросом (для экрана /settings)."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT timezone, reminder_mode,
                      time_morning, time_lunch, time_evening, time_night,
                      daily_plan_enabled, daily_plan_time, caregiver_enabled,
                      hearts, strict_mode, strict_mode_hours, reminder_repeat_hours,
                      caregiver_code, wishes_enabled, wishes_tg_notify
               FROM users WHERE telegram_id = %s""",
            (telegram_id,)
        ).fetchone()


# ── Сердечки (G1) и строгий режим (G2) ──────────────────────────────────────

def apply_intake_hearts(user_id: int, new_status: str, old_status) -> int:
    """Корректирует счётчик сердечек при смене статуса приёма. Возвращает новое значение.

    +1 за taken, −1 за skipped, 0 за pending/нет. delta = вклад(new) − вклад(old) —
    идемпотентно к повторам и переотметкам. Нижняя граница 0 (GREATEST).
    """
    contrib = {"taken": 1, "skipped": -1}
    delta = contrib.get(new_status, 0) - contrib.get(old_status, 0)
    with get_connection() as conn:
        if delta == 0:
            row = conn.execute("SELECT hearts FROM users WHERE id = %s", (user_id,)).fetchone()
            return row["hearts"] if row else 0
        row = conn.execute(
            "UPDATE users SET hearts = GREATEST(0, hearts + %s) WHERE id = %s RETURNING hearts",
            (delta, user_id)
        ).fetchone()
        return row["hearts"] if row else 0


def get_hearts(telegram_id: int) -> int:
    """Возвращает количество сердечек пользователя."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT hearts FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return row["hearts"] if row else 0


# ── Ф15: соцмеханика пожеланий (тестовый функционал) ────────────────────────

# Минимум участников в пуле (включая отправителя), чтобы разрешить отправку.
# При меньшем — единственным получателем был бы сам отправитель → блок.
WISH_MIN_POOL = 2
# Антифрод: лимит отправок в сутки (UTC-день) на одного отправителя.
WISH_DAILY_LIMIT = 20


def set_wishes_enabled(telegram_id: int, enabled: bool) -> None:
    """Включает/выключает участие в соцмеханике пожеланий."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET wishes_enabled = %s WHERE telegram_id = %s",
            (1 if enabled else 0, telegram_id),
        )


def is_wishes_enabled(telegram_id: int) -> bool:
    """True, если юзер участвует в соцмеханике пожеланий."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT wishes_enabled FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        return bool(row and row["wishes_enabled"])


def count_wish_pool() -> int:
    """Размер пула участников (всех, у кого включена механика)."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT COUNT(*) AS n FROM users WHERE wishes_enabled = 1"
        ).fetchone()["n"]


def count_wishes_sent_today(sender_user_id: int) -> int:
    """Сколько пожеланий отправитель послал за текущий UTC-день (антифрод-лимит)."""
    today = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    with get_connection() as conn:
        return conn.execute(
            "SELECT COUNT(*) AS n FROM wishes_sent "
            "WHERE sender_id = %s AND LEFT(created_at, 10) = %s",
            (sender_user_id, today),
        ).fetchone()["n"]


def pick_wish_recipient(sender_user_id: int) -> int | None:
    """Случайный получатель из пула, кроме самого отправителя. None если пусто."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT id FROM users WHERE wishes_enabled = 1 AND id != %s "
            "ORDER BY random() LIMIT 1",
            (sender_user_id,),
        ).fetchone()
        return row["id"] if row else None


def create_wish(sender_user_id: int, recipient_user_id: int, preset_code: str) -> int:
    """Создаёт запись пожелания (доставлено в inbox получателя). Возвращает id."""
    with get_connection() as conn:
        return conn.execute(
            "INSERT INTO wishes_sent (sender_id, recipient_id, preset_code) "
            "VALUES (%s, %s, %s) RETURNING id",
            (sender_user_id, recipient_user_id, preset_code),
        ).fetchone()["id"]


def get_wish_inbox(recipient_user_id: int) -> list:
    """Новые (без реакции) пожелания для получателя — отдаём в всплывашку."""
    with get_connection() as conn:
        return conn.execute(
            "SELECT id, preset_code, created_at FROM wishes_sent "
            "WHERE recipient_id = %s AND reaction IS NULL "
            "ORDER BY created_at DESC",
            (recipient_user_id,),
        ).fetchall()


def react_to_wish(wish_id: int, recipient_user_id: int, reaction: str) -> int | None:
    """Ставит реакцию на пожелание (если принадлежит получателю и без реакции).

    Возвращает sender_id, либо None если нечего обновлять.
    """
    with get_connection() as conn:
        row = conn.execute(
            "UPDATE wishes_sent SET reaction = %s, status = 'reacted', "
            "reacted_at = to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') "
            "WHERE id = %s AND recipient_id = %s AND reaction IS NULL "
            "RETURNING sender_id",
            (reaction, wish_id, recipient_user_id),
        ).fetchone()
        return row["sender_id"] if row else None


def set_wishes_tg_notify(telegram_id: int, enabled: bool) -> None:
    """Вкл/выкл TG-дайджест о реакциях (in-app показ работает независимо)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET wishes_tg_notify = %s WHERE telegram_id = %s",
            (1 if enabled else 0, telegram_id),
        )


def get_wish_ack_summary(sender_user_id: int) -> dict:
    """Кумулятивные отклики на пожелания отправителя (для in-app карточки)."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT "
            "COALESCE(SUM((reaction = 'helped')::int), 0) AS helped, "
            "COALESCE(SUM((reaction = 'supported')::int), 0) AS supported "
            "FROM wishes_sent WHERE sender_id = %s AND reaction IS NOT NULL",
            (sender_user_id,),
        ).fetchone()
        return {"helped": row["helped"], "supported": row["supported"]}


def get_wish_digest_candidates() -> list:
    """Юзеры с включённым TG-дайджестом, у кого есть нерассланные отклики.

    Возвращает [{user_id, telegram_id, timezone, helped, supported}].
    """
    with get_connection() as conn:
        return conn.execute(
            "SELECT u.id AS user_id, u.telegram_id, u.timezone, "
            "  SUM((w.reaction = 'helped')::int) AS helped, "
            "  SUM((w.reaction = 'supported')::int) AS supported "
            "FROM users u JOIN wishes_sent w ON w.sender_id = u.id "
            "WHERE u.wishes_tg_notify = 1 AND u.wishes_enabled = 1 "
            "  AND w.reaction IS NOT NULL AND w.sender_digest_at IS NULL "
            "GROUP BY u.id, u.telegram_id, u.timezone"
        ).fetchall()


def mark_wish_reactions_digested(sender_user_id: int) -> None:
    """Помечает отклики отправителя как вошедшие в дайджест (дедуп повторной рассылки)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE wishes_sent SET sender_digest_at = "
            "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') "
            "WHERE sender_id = %s AND reaction IS NOT NULL AND sender_digest_at IS NULL",
            (sender_user_id,),
        )


# ── Ачивки (F12a) ────────────────────────────────────────────────────────────

def count_total_taken(user_id: int) -> int:
    """Всего приёмов taken по СОБСТВЕННЫМ лекарствам (dependent_id IS NULL)."""
    with get_connection() as conn:
        row = conn.execute(
            """SELECT COUNT(*) AS n FROM intake_log il
                 JOIN medications m ON m.id = il.medication_id
                WHERE m.user_id = %s AND m.dependent_id IS NULL
                  AND il.status = 'taken'""",
            (user_id,)
        ).fetchone()
        return row["n"] if row else 0


def has_any_care_link(user_id: int) -> bool:
    """Есть хотя бы одна активная связь «Забота» (F7 любой стороной или F8)."""
    with get_connection() as conn:
        row = conn.execute(
            """SELECT EXISTS(
                   SELECT 1 FROM caregiver_links
                    WHERE status = 'active' AND (caregiver_id = %s OR dependent_id = %s)
                   UNION ALL
                   SELECT 1 FROM dependent_shares
                    WHERE status = 'active' AND (owner_user_id = %s OR viewer_user_id = %s)
               ) AS e""",
            (user_id, user_id, user_id, user_id)
        ).fetchone()
        return bool(row["e"]) if row else False


def get_achievements(user_id: int) -> list[str]:
    """Список разблокированных кодов ачивок пользователя."""
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT code FROM achievements WHERE user_id = %s", (user_id,)
        ).fetchall()
        return [r["code"] for r in rows]


def unlock_achievements(user_id: int, codes: list[str]) -> list[str]:
    """Разблокирует коды (ON CONFLICT DO NOTHING). Возвращает ТОЛЬКО новые."""
    if not codes:
        return []
    with get_connection() as conn:
        newly = []
        for code in codes:
            row = conn.execute(
                """INSERT INTO achievements (user_id, code) VALUES (%s, %s)
                   ON CONFLICT (user_id, code) DO NOTHING RETURNING code""",
                (user_id, code)
            ).fetchone()
            if row:
                newly.append(row["code"])
        return newly


def set_strict_mode(telegram_id: int, enabled: bool, hours: int = None, minutes: int = 0):
    """Включает/выключает строгий режим; опционально обновляет порог в часах/минутах."""
    with get_connection() as conn:
        if hours is None:
            conn.execute(
                "UPDATE users SET strict_mode = %s WHERE telegram_id = %s",
                (1 if enabled else 0, telegram_id)
            )
        else:
            conn.execute(
                "UPDATE users SET strict_mode = %s, strict_mode_hours = %s, strict_mode_minutes = %s WHERE telegram_id = %s",
                (1 if enabled else 0, hours, minutes, telegram_id)
            )


def get_daily_plan_settings(telegram_id: int) -> dict:
    """Возвращает настройки плана дня: {enabled, time}."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT daily_plan_enabled, daily_plan_time FROM users WHERE telegram_id = %s",
            (telegram_id,)
        ).fetchone()
        if row:
            return {"enabled": bool(row["daily_plan_enabled"]), "time": row["daily_plan_time"] or "08:00"}
        return {"enabled": True, "time": "08:00"}


def set_daily_plan_enabled(telegram_id: int, enabled: bool):
    """Включает или выключает план дня."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET daily_plan_enabled = %s WHERE telegram_id = %s",
            (1 if enabled else 0, telegram_id)
        )


def set_daily_plan_time(telegram_id: int, time_str: str):
    """Устанавливает время отправки плана дня."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE users SET daily_plan_time = %s WHERE telegram_id = %s",
            (time_str, telegram_id)
        )


def get_schedules_for_user(telegram_id: int) -> list:
    """Возвращает все активные правила расписания для одного пользователя."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT u.telegram_id, u.timezone,
                      m.id AS medication_id, m.name, m.dosage AS med_dosage, m.meal_relation,
                      m.dependent_id AS dependent_id, m.unit_dose_value, m.unit_dose_label,
                      sr.reminder_time, sr.frequency, sr.interval_days,
                      sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage AS rule_dosage, sr.dose_cycle,
                      d.name AS dependent_name
               FROM users u
               JOIN medications m ON m.user_id = u.id AND m.active = 1
               JOIN schedule_rules sr ON sr.medication_id = m.id
               LEFT JOIN dependents d ON d.id = m.dependent_id
               WHERE u.telegram_id = %s AND m.paused = 0
               ORDER BY m.id, sr.reminder_time""",
            (telegram_id,)
        ).fetchall()


def get_own_schedules_for_user(telegram_id: int) -> list:
    """Как get_schedules_for_user, но только собственные лекарства пользователя
    (dependent_id IS NULL) — для отображения подопечного у помощника без утечки
    локальных близких самого подопечного."""
    with get_connection() as conn:
        return conn.execute(
            """SELECT u.telegram_id, u.timezone,
                      m.id AS medication_id, m.name, m.dosage AS med_dosage, m.meal_relation,
                      m.unit_dose_value, m.unit_dose_label,
                      sr.reminder_time, sr.frequency, sr.interval_days,
                      sr.weekdays, sr.month_day, sr.anchor_date, sr.dosage AS rule_dosage, sr.dose_cycle,
                      NULL AS dependent_name
               FROM users u
               JOIN medications m ON m.user_id = u.id AND m.active = 1
               JOIN schedule_rules sr ON sr.medication_id = m.id
               WHERE u.telegram_id = %s AND m.paused = 0 AND m.dependent_id IS NULL
               ORDER BY m.id, sr.reminder_time""",
            (telegram_id,)
        ).fetchall()


def delete_user_data(telegram_id: int) -> list:
    """Удаляет все данные пользователя. Возвращает список ID удалённых лекарств."""
    with get_connection() as conn:
        user = conn.execute(
            "SELECT id FROM users WHERE telegram_id = %s", (telegram_id,)
        ).fetchone()
        if not user:
            return []
        user_id = user["id"]
        med_ids = [r["id"] for r in conn.execute(
            "SELECT id FROM medications WHERE user_id = %s", (user_id,)
        ).fetchall()]
        if med_ids:
            conn.execute("DELETE FROM intake_log WHERE medication_id = ANY(%s)", (med_ids,))
            conn.execute("DELETE FROM schedule_rules WHERE medication_id = ANY(%s)", (med_ids,))
            conn.execute("DELETE FROM medications WHERE user_id = %s", (user_id,))
        conn.execute("DELETE FROM dependents WHERE user_id = %s", (user_id,))
        conn.execute(
            "DELETE FROM caregiver_links WHERE caregiver_id = %s OR dependent_id = %s",
            (user_id, user_id),
        )
        # Ф15: пожелания, где юзер был отправителем или получателем
        conn.execute(
            "DELETE FROM wishes_sent WHERE sender_id = %s OR recipient_id = %s",
            (user_id, user_id),
        )
        # F12a: ачивки (FK без ON DELETE CASCADE — иначе блокируют удаление users)
        conn.execute("DELETE FROM achievements WHERE user_id = %s", (user_id,))
        conn.execute("DELETE FROM users WHERE telegram_id = %s", (telegram_id,))
        return med_ids


def get_admin_stats() -> dict:
    """Возвращает статистику для админ-панели."""
    today = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    with get_connection() as conn:
        total_users = conn.execute("SELECT COUNT(*) AS n FROM users").fetchone()["n"]
        total_meds = conn.execute(
            "SELECT COUNT(*) AS n FROM medications WHERE active = 1"
        ).fetchone()["n"]
        active_today = conn.execute(
            """SELECT COUNT(DISTINCT m.user_id) AS n FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               WHERE LEFT(i.taken_at, 10) = %s""",
            (today,)
        ).fetchone()["n"]
        return {"total_users": total_users, "total_meds": total_meds, "active_today": active_today}


def get_today_intake_statuses(telegram_id: int, start_utc: str, end_utc: str) -> dict:
    """Возвращает {(medication_id, scheduled_time): status} для записей в локальных сутках пользователя."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT i.medication_id, i.scheduled_time, i.status
               FROM intake_log i
               JOIN medications m ON m.id = i.medication_id
               JOIN users u ON u.id = m.user_id
               WHERE u.telegram_id = %s AND i.taken_at >= %s AND i.taken_at < %s""",
            (telegram_id, start_utc, end_utc)
        ).fetchall()
    return {(r["medication_id"], r["scheduled_time"]): r["status"] for r in rows}


def log_intake(medication_id: int, scheduled_time: str, status: str,
               start_utc: str, end_utc: str):
    """Записывает факт приёма или пропуска лекарства. Обновляет запись если уже есть за сегодня.

    status="pending" отменяет отметку: удаляет запись (нет записи = pending).
    Возвращает прежний статус записи за сегодня (или None, если записи не было).
    """
    now_utc = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')
    with get_connection() as conn:
        existing = conn.execute(
            """SELECT id, status FROM intake_log
               WHERE medication_id = %s AND scheduled_time = %s
               AND taken_at >= %s AND taken_at < %s""",
            (medication_id, scheduled_time, start_utc, end_utc)
        ).fetchone()
        if status == "pending":
            if existing:
                conn.execute("DELETE FROM intake_log WHERE id = %s", (existing["id"],))
                return existing["status"]
            return None
        if existing:
            conn.execute(
                "UPDATE intake_log SET status = %s, taken_at = %s WHERE id = %s",
                (status, now_utc, existing["id"])
            )
            return existing["status"]
        # AX1: ON CONFLICT — при гонке двух параллельных INSERT один вставит,
        # второй обновит существующую строку вместо создания дубля.
        conn.execute(
            """INSERT INTO intake_log (medication_id, scheduled_time, status, taken_at)
               VALUES (%s, %s, %s, %s)
               ON CONFLICT (medication_id, scheduled_time, (LEFT(taken_at, 10)))
               DO UPDATE SET status = EXCLUDED.status, taken_at = EXCLUDED.taken_at""",
            (medication_id, scheduled_time, status, now_utc)
        )
        return None


# ── Учёт запаса таблеток (F5) ───────────────────────────────────────────────

def set_medication_stock(medication_id: int, user_id: int, stock_qty: float):
    """Устанавливает остаток (включает трекинг)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET stock_qty = %s WHERE id = %s AND user_id = %s",
            (stock_qty, medication_id, user_id)
        )


def add_medication_stock(medication_id: int, user_id: int, amount: float):
    """Прибавляет amount к остатку (пополнение упаковкой). Если трекинг был выключен — включает."""
    with get_connection() as conn:
        row = conn.execute(
            "SELECT stock_qty FROM medications WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        ).fetchone()
        base = (row["stock_qty"] if row and row["stock_qty"] is not None else 0)
        conn.execute(
            "UPDATE medications SET stock_qty = %s WHERE id = %s AND user_id = %s",
            (base + amount, medication_id, user_id)
        )


def set_units_per_dose(medication_id: int, user_id: int, units: float):
    """Устанавливает расход единиц за один приём."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET units_per_dose = %s WHERE id = %s AND user_id = %s",
            (units, medication_id, user_id)
        )


def set_low_stock_days(medication_id: int, user_id: int, days: int):
    """Устанавливает порог предупреждения (в днях)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET low_stock_days = %s WHERE id = %s AND user_id = %s",
            (days, medication_id, user_id)
        )


def set_course_total(medication_id: int, user_id: int, total):
    """Устанавливает лимит курса (число приёмов) или снимает его (None = бессрочно).

    «Продолжить» завершённый курс = total=None: лекарство продолжает приёмы
    по расписанию без отметки «завершён»."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET course_total = %s WHERE id = %s AND user_id = %s",
            (total, medication_id, user_id)
        )


def disable_stock_tracking(medication_id: int, user_id: int):
    """Выключает учёт запаса (stock_qty = NULL)."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE medications SET stock_qty = NULL WHERE id = %s AND user_id = %s",
            (medication_id, user_id)
        )


def apply_intake_stock(medication_id: int, new_status: str, old_status, scheduled_time=None, day=None):
    """Корректирует остаток при отметке приёма. Возвращает dict состояния после или None.

    Идемпотентно: списывает units_per_dose только при переходе в `taken`,
    возвращает при уходе из `taken`. `changed=True` — если остаток изменился.
    None — если трекинг выключен (stock_qty IS NULL) или лекарство не найдено.

    Поприёмная доза: если у правила (по scheduled_time) задана своя dosage —
    списываем по ней (dosage/unit_dose_value), иначе по единой units_per_dose.
    """
    with get_connection() as conn:
        # AX2: FOR UPDATE сериализует параллельные списания одного лекарства
        # (кнопка «Выпил всё» шлёт N параллельных запросов) — без блокировки
        # строки два read-modify-write теряли бы часть изменений (lost update).
        row = conn.execute(
            "SELECT stock_qty, units_per_dose, low_stock_days, unit_dose_value "
            "FROM medications WHERE id = %s FOR UPDATE",
            (medication_id,)
        ).fetchone()
        if row is None or row["stock_qty"] is None:
            return None
        units = row["units_per_dose"] or 1
        # Поприёмная (F11-E) / цикловая (F11-F) доза перекрывает общую.
        # Цикл (dose_cycle, по дате `day`) приоритетнее фикс-дозы правила.
        if scheduled_time is not None and row["unit_dose_value"]:
            r = conn.execute(
                "SELECT dosage, dose_cycle, anchor_date FROM schedule_rules "
                "WHERE medication_id = %s AND reminder_time = %s "
                "ORDER BY (dose_cycle IS NOT NULL) DESC, (dosage IS NOT NULL) DESC LIMIT 1",
                (medication_id, scheduled_time)
            ).fetchone()
            dose_token = None
            if r:
                if r["dose_cycle"] and day is not None:
                    from schedule_utils import cycle_dose_for_day
                    dose_token = cycle_dose_for_day(r["dose_cycle"], r["anchor_date"], day)
                elif r["dosage"]:
                    dose_token = r["dosage"]
            if dose_token:
                dv = _parse_dose_number(dose_token)
                if dv:
                    units = dv / row["unit_dose_value"]
        qty = row["stock_qty"]
        changed = False
        if new_status == "taken" and old_status != "taken":
            qty = max(0, qty - units)
            changed = True
        elif old_status == "taken" and new_status != "taken":
            qty = qty + units
            changed = True
        if changed:
            conn.execute("UPDATE medications SET stock_qty = %s WHERE id = %s", (qty, medication_id))
        return {"stock_qty": qty, "units_per_dose": units,
                "low_stock_days": row["low_stock_days"], "changed": changed}
